### ISSUE TITLE
Metadata causes photo upload to crash (again!)

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1001]
I've tried this on 12.4.7 and 12.4.3
Uploading the attached photo with metadata will crash the Photos module.  Uploading with the metadata stripped works.  The symptom is the same as for issue 981, which was fixed a while ago.  This is a different camera.  Photos from the original camera (the one mentioned in issue 981) can be uploaded, so presumably this is something specific to this camera's metadata.
![2Photo_With_Meta](https://user-images.githubusercontent.com/64681720/112232763-3c026780-8c8d-11eb-9e65-d99e1ca8b214.JPG)
![2Photo_Without_Meta](https://user-images.githubusercontent.com/64681720/112232765-3d339480-8c8d-11eb-9b2a-7ee730c658ab.JPG)

**Comment by jennyq** [comment]
Thanks @CWalkden ! We're looking into it.

**Comment by chuqtas** [comment]
Hi, I'm the user who reported the bug to @CWalkden.  I've done some more testing and I've found the cause of this issue is the "latitude" field.  Longitude and altitude are fine!  I've tested by deleting *only* the latitude (the uploads works fine) and also deleting all fields *except* the latitude (the upload fails).

![image](https://user-images.githubusercontent.com/51102336/112473364-61dd5880-8dc2-11eb-9613-c9b77cd032ba.png)

**Comment by jennyq** [comment]
Thanks @chuqtas ! Yes, it was indeed caused by the GPS info. For some reason, the data format in the "latitude" has been changed. Fixed. 

Note: Google GeoCoding now requires an API key. To make location show up with the photos uploaded, you'll need to add your API key in the setting https://www.example.com/settings/module/locations/#id_google_geocoding_api_key
