### ISSUE TITLE
Endless loop for user signup

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1111]
We have a problem that goes like this:
1. Member of the public fills in a form that asks for their email address.  Tendenci has not seen them before, so a User profile is created for them with the 'Interactive' field set to 'Not Interactive'.
2. At some later date, the User decides to create a user profile.  But their request is rejected because the email address is in use.
3. The User goes to the password reset page and enters their email address.  But Tendenci gives them an error saying that there is no User record for that email address.

To fix this I went into their profile via the administrator interface and changed them to 'Interactive'.  They were then able to reset their password.

In this case the error message at step 3 was misleading.  Can this be fixed?  
We'd like for a User to make their profile interactive.  Is there a way that they can do this?

settings/module/forms/#id_form_submission_create_user  is set to FALSE.  The system creates a User in this case because it requires payment.

**Comment by rob-hills** [comment]
This issue is a serious obstacle to Engagement IMHO which is a key tenet of Tendenci and deserves high priority I think.

**Comment by jennyq** [comment]
If non-interactive users apply memberships, they do have an option to activate their accounts. 

Changed the wording to no "active" user account instead of no "associated" user account https://github.com/tendenci/tendenci/commit/cb2950757f6bef22d006bbcca23c997f2300078b.

**Comment by CWalkden** [comment]
What's the purpose of a Not Interactive account?  Would it be logical to set it to Interactive if a password reset is requested?

**Comment by jennyq** [comment]
The purpose of a Non Interactive account - Even though they cannot log in, non interactive users can still receive newsletters. That's all they need for some sites. 

Automatically activating their accounts when a password reset is requested is definitely not an option, as it would give hackers a tool to mess up with the site easily. There are always trade offs between security and convenience.  Would it be better if, in the pw reset email, instead of a pw reset link, they receive a link to activate their accounts?

**Comment by CWalkden** [comment]
> Would it be better if, in the pw reset email, instead of a pw reset link, they receive a link to activate their accounts?

Yes - that sounds like a good solution!  At the moment they don't receive anything and don't know what is going on.

By the way, this was reported once last month, then twice last week.  We have about 3000 users, about 1000 of whom are members.

**Comment by jennyq** [comment]
Ok, will check with the team and work on it if no objections.

**Comment by ndavis2** [comment]
I'd imagine that if the self-registration is enabled, a user should be able to request to activate their profile with an activation link sent to their email, rather than the system automatically updating their account to interactive, if that makes sense.  

This prevents that roadblock of user signup (and misleading error message) while keeping the layer of security with an email check..

The system should/will recognize that the user email is in the database and send an activation link to their email when they try to proceed with authenticating their account by logging in for the first time.

**Comment by lashirley21** [comment]
/settings/module/users/#id_selfregistration ✅
