### ISSUE TITLE
Photo metadata causes crash (again!)

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1145]
Same symptom as issues 1001 and 981.
Tendenci 14.3.2.  Photos module.

Uploading the file "No_Metadata" is fine, but "With_Metadata" fails:
![image](https://user-images.githubusercontent.com/64681720/207024772-d5253bd4-d9d5-4d38-acc2-aa7a79a1f53f.png)

I've included the files below so that they can be checked.  First one is With_Metadata.jpg, second is No_Metadata.jpg
The problem happened with every photo from this camera.

![With_Metadata](https://user-images.githubusercontent.com/64681720/207024492-2e4e87b7-cfe5-480f-bf1a-efc88f3328b3.jpg)

![No_Metadata](https://user-images.githubusercontent.com/64681720/207024473-112ec8de-b771-44f2-9b8c-ec56ff0df064.jpg)

**Comment by lashirley21** [comment]
I also recently had problems uploading .jpg files. Interesting.

**Comment by jennyq** [comment]
@CWalkden, 

Thank you for reporting the issue. We'll look into it. cc @lashirley21.

**Comment by jennyq** [comment]
Pushed out a fix https://github.com/tendenci/tendenci/commit/e3a7c2cc42054cf9be3bc53493f0a4758ef7456a.

It's a different cause than the ones in 1001 and 981. What happened is that the GPS info has a different format in that photo. For example, what's in the latitude is (nan, nan, nan) instead of a tuple like (41.0, 10.0, 38.5). When you tried to convert any one of them to a float number, it throws "ZeroDivisionError: division by zero" because the latitude is a tuple of the values in the 'PIL.TiffImagePlugin.IFDRational' format with both denominator and numerator as 0.
