### ISSUE TITLE
Error python deploy.py

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#361]
I am getting the following error when install tendenci locally.
python deploy.py
python deploy.py
Error: One or more models did not validate:
memberships.membershipdefault: 'directory' has a relation with model <class 'tendenci.addons.directories.models.Directory'>, which has either not been installed or is abstract.

Traceback (most recent call last):
  File "deploy.py", line 3, in <module>
    subprocess.check_call(['python', 'manage.py',  'syncdb', '--noinput'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'syncdb', '--noinput']' returned non-zero exit status 1

I checked the tendenci.addons.directories and is there. Any suggestions?

**Comment by eschipul** [comment]
It is an error being generated by South migration which is part of the normal process of setting up a site. You can probably bump past it with a few --fake migrations on that module but I'm not sure without more information.

Further, it's probably our fault as sometimes we have a dependency on a development box that is missing from requirements.txt or a pinned requirement in settings.py in core if you are on T5. 

So let's work through this. A few questions:

Ideally you are installing on 
1) Ubuntu 14.04 LTs
2) You have all updates in stalled (e.g. sudo apt-get update && sudo apt-get upgrade -y)
3) You are running Postgres with GIS enabled (if not required it soon will be so may as well start with GIS and GDAL on your template.
4) Python 2.7.x as 3.3 should work on Tendenci 6 with Django 1.6 but we haven't run tests on it yet for the installation instructions.
5) Version of NGINX
6) Gunicorn or Uwsgi
7) Version of Postgres (9.1 to 9.4 are all working in our various server farms)

Things that would help me diagnose the problem as well is to know the method you are using to install Tendenci. We are half on the Tendenci 6 branch which is not currently master on github.com and is actually under very active development on our private git server and hasn't been pushed out. Why? Because we changed the templating system and it blows out layouts that were done the old way.

So I need more info to trouble shoot the issue. Or temporary access to your server so I can take a look (then of course remove my key if this is a route you want to take but I'd be happy to take a look.)

If installing Tendenci 5.x be sure to check the hidden .env file for connection string issues. That file, which I regret introducing so blame that on me - it was when I drank the Keroku cool-aid and I should have listened to my other developers and not done it. But... if on 5.x double check your .env file in the root.

More info and I can be more helpful. Would love to help you get it up and running. Thanks!

**Comment by jennyq** [comment]
@dco5, thank you for trying Tendenci and for reporting the error to us. The error has been fixed. Please try again. As @eschipul pointed out, the current master branch will soon be replaced by the Tendenci 6 - just something to be aware of. Thanks!
