### ISSUE TITLE
Add Corp. Member produces 404

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#371]
After navigating to http://192.168.56.101/corporatememberships/applications/mycorps/ as admin I use the Corporate Memberships dropdown menu and click Add Corp. Member. and see a 404.

```
Page not found (404)
Request Method:	GET
Request URL:	http://192.168.56.101/corporatememberships/applications/add/
Raised by:	tendenci.apps.corporate_memberships.views.corpmembership_add
```

**Comment by eschipul** [comment]
@goetzk - duplicated it. definite bug. 

notes to self, 
duplicated it from the bootstrap3 black nav bar and from the link in the admin section that links to add corporate memberships. It may be a fixtures issue but either way should not create a 404.

**Comment by eschipul** [comment]
https://github.com/tendenci/tendenci/issues/371

@jennyq - I thought this might be a basic urls.py issue I might be able to solve. Nope - can't figure it out. I can duplicate the error (on my local) dev I suspect it is the switch with django 1.8 to "model" instead of "module". I'm probably wrong but can you please teach me how to trouble shoot this one? This is the only commit that looks like it might relate.

https://github.com/tendenci/tendenci/blob/30d67916096dd6f57f0ae81f2a2b129392f75d37/tendenci/apps/corporate_memberships/utils.py

t5 sites are still working correctly (client name removed but you get the idea)
http://www.example.org/corporatememberships/applications/add/
my local dev on t7 clean install with load_npo_defaults throws a 404 as @goetzk noted above
http://192.168.184.130/corporatememberships/applications/add/

Symptom is specifically this on my local:
http://192.168.184.130/corporatememberships/applications/add/
generates a 404 and the log files aren't telling me anything when I tail them.

I tried but failed figuring this one out. I did try every variation I could think of after looking at urls.py, models.py, admin.py and views.py in the corporatememberships module. Any hints to point me in the right direction or am I just missing something obvious?

![screen shot 2015-08-29 at 4 26 03 pm](https://cloud.githubusercontent.com/assets/153359/9564374/d2137ab4-4e6a-11e5-8d3d-37725618fd31.png)

I should mention as well that I did add membership types prior to accessing dev so I don't believe those are the issue (but again - I specialize in being wrong about stuff so it's possible.)

**Comment by jennyq** [comment]
@goetzk In order to add a corporate membership, the site needs to have a corporate membership application available. Please check if you have that set up at admin backend /admin/corporate_memberships/corpmembershipapp/.

You've brought up a very good point. Maybe we should redirect admin to the admin backend in this case so that they can add an application there.  A 404 page is not intuitive. 

Please also note that there are some formatting issues in the corporate membership. We'll address it when we get the chance or you're welcome to submit pull-requests.

**Comment by jennyq** [comment]
Another issue I've noticed - the "Add Corporate Membership Application" form has all the checkboxes checked for Show, Required, Admin Only for all fields. /admin/corporate_memberships/corpmembershipapp/add/. It is not supposed to be that way - needs to be fixed too.

**Comment by jennyq** [comment]
@eschipul The 404 is thrown from here https://github.com/tendenci/tendenci/blob/master/tendenci/apps/corporate_memberships/views.py#L183

**Comment by eschipul** [comment]
thank you @jennyq - I'll give it another try tomorrow to see if I can help without breaking things.

**Comment by goetzk** [comment]
http://192.168.56.101:8000/corporatememberships/applications/mycorps/ no longer throws a 404.

**Comment by eschipul** [comment]
Thanks. We're working to improve the default fixtures as well to prevent relational database errors in the future. We appreciate your help getting finding the pain points!
