### ISSUE TITLE
Status of expired members doesn't change

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#372]
When i log in as admin and view my membership list (using the provided NGO data) at http://192.168.56.101/admin/memberships/membershipdefault/?o=3 I can't change the status of members from active.

I select id's 1007, 1008 and 1009 and use Action 'Expire Selected' but their status' don't change

HOWEVER if I renew a member so they expire in the future and use the expire action on them they are marked as expired. This suggests a problem with the expiring sql query.

From this I feel there are two problems:
* members with expiry dates in the past aren't marked as expired but active
* members who have been manually expired still have an expiry date in the future

**Comment by eschipul** [comment]
@goetzk - I think we have two different issues here actually.

This one sounds like a bug --> "members with expiry dates in the past aren't marked as expired but active". It might be something as simple as the nightly cron job isn't running to expire them but still that is a bug in the system or a bug in the installation instructions that is probably my fault.

Second issue --> "members who have been manually expired still have an expiry date in the future"

That one doesn't sound like a bug. Although I can't be sure as I can't tell exactly which object you are referring to when you say "Action 'Expire Selected' but their status' don't change".

status is a boolean that means "exists or not" basically to facitate soft deletes and prevent cascading object deletes like in Django 1.4. So even a non-interactive user, meaning one that can't login, has a status=1 or True.

status_detail is a literal intended to facilitate work flow. Like an event that is added by a user shouldn't go live on the calendar until approved. So it should have a status=true status_detail="pending" or similar. 

Starting with Tendenci 5+ we realized we were missing historical reporting of a member's membership over time. Why does someone let their membership lapse for example? The first step to fix it is to make it visible to the board imho. Hence while it is possible to bump the expiration date of a membership application record into the future, it is better for them to make a new record.

In this scenario the old membership application associated with a user (an attribute of a user) becomes a status=1 (so we can report on it) and a status_detail="expired". That is the intent at least. If it is not working that way, and it is not one of the more likely options of the cron job failing or a bug, then it is also a bug and probably deserves it's own issue for tracking purposes.

Here is the vision - a leaflet.js map of your membership evolving over time. How cool would that be? So we had to get the data structure in place first. If it's broken, please help me understand further so we as a team can figure it out and help everyone. Thank you!

**Comment by dco5** [comment]
Ok, I saw this problem and started debugging with break points and analysing the code. Using the admin action of __Expire Selected__ in /admin/memberships/membershipdefault/ calls  

__def expire_selected(modeladmin, request, queryset):__
...
  __if not membership.is_expired():
      membership.expire(request_user=request.user)__

If the membership is not expire then expire it. 
So it goes inside __is_expired__ and checks the status, if it has an expiration date,  if the expiration date, and if the membership is still in grace period.

After all this if the membership is expired it will return True if it is expired.
So if the member is already expired because it is past the expiration date and the grace period, but it still has an active status, it will not be expire by this action because __membership.is_expired()__ will always return __True__ and __not True == False__ so the IF statement of __expire_selected__ will always be false, and the member will not be expire by the action.

So I do guess a problem with a cron job not expiring the members that are past the expiration date and the grace period.

I am sorry if I am not been clear with my explanation. I can see it in my head very clearly and understand it, but it is hard for me to explain things sometimes.

**Comment by dco5** [comment]
Also in the __expired_selected__ there is a filter:
    memberships = queryset.filter(
        status=True,
        status_detail='active',
        application_approved=True,
    )
So at the end memberships will only contain members that are active. So I think the 
      if not membership.is_expired():
is not necessary, but I might be wrong. But still if I remove the  __if not membership.is_expired():__ it will not expire the member because __ def expire(self, request_user):__ will check if the member is approved and it will go into the is_expired method and again it will say it is expired already but it will still have an active status.

**Comment by eschipul** [comment]
Haven't forgotten about this one....

**Comment by jennyq** [comment]
Pushed out a fix https://github.com/tendenci/tendenci/commit/a6cc278805d6945b4ff526c377947b77302bc8ea

Thanks guys!
