### ISSUE TITLE
Too many sources of install documentation

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#379]
Hi,
I feel there are too many places describing how to install tendenci using slightly different instructions.

tendency and tendency-project-template both have read me files with instructions as well as the two copies of the install guide for remote and local users shipped in tendency and available on read the docs. 

I'd like to suggest that there should be fewer places.

* tendenci's read me can (should?) point to the install instructions it ships
* local and remote install instructions should be combined. (I'm having a go at this as i write this so will have some idea of how practical it is soon).
* I'm not sure what to do with the read me of tendenci-project-template other than to strongly recommend another source of documentation in the file (e.g., that shipped by tendency) or some sort of git upload hook that updates both read me files in sync.

What are your thoughts on this?

**Comment by goetzk** [comment]
I found another - github wiki. https://github.com/tendenci/tendenci/wiki

**Comment by goetzk** [comment]
I've updated the title to stipulate install doc - i think there are too many sources for documentation in general still but thought that might be worth its own ticket.
General documentaiton:
- tendenci read the docs e.g. https://tendenci.readthedocs.org/en/latest/topic-guides/boxes.html
- tendenci community, https://community.tendenci.com/
- help pages, https://www.tendenci.com/help-files/
- github wiki, https://github.com/tendenci/tendenci/wiki

That is the basis of any new ticket about too many sources of documentation :)

Recap of this ticket:
- readme points to install instructions in git and read the docs
- install.md has been removed
- local and remote install instructions have been combined

github wiki still exists and the tendenci project template has its own instructions still.

**Comment by eschipul** [comment]
Excellent point.

- killed content from the wiki and linked it to the readthedocs page and the forum https://github.com/tendenci/tendenci/wiki

community.tendenci.com will soon redirect to https://www.tendenci.com/forums/ once we move over the content of value from the older site. Needs a link to register in the nav. To do list. But can register now at 

Helpdesk - not sure how to solve that one because I agree it comes up very high in search but doesn't make it easy to distinguish between versions of tendenci. Help files from versions 4 through 7 are on there. Still thinking.

Leaving this open until we find a balance between the three (readthedocs, forums in tendenci.com, and helpfiles.) Also considering if we have enough critical mass to create a freenode irc room. This one stays open as a work in progress.

**Comment by eschipul** [comment]
Note - also turned on allow self reg on tendenci.com so people can create an account at 
https://www.tendenci.com/accounts/register/

And login at
https://www.tendenci.com/accounts/login/

This is needed to post in the forums.

**Comment by eschipul** [comment]
Strongly agree. However it is a huge issue beyond the scope of one issue. I need to figure out where to put the roadmap and list this type of thing as a project and divide it up by module. But yes, this last weekend I wasted 5 hours personally because I was unaware a setting had to have an explicit protocol in one place (site settings) and no protocol in /admin/sites/ which makes no sense to me.

So yes I'm in strong agreement. I'd love to see more documentation pull requests. This one however is simply too broad to be actionable for all of us to tackle as one issue. Documentation and Unit Tests are the known Global Warming and Chernobyl issues for Tendenci. We just attacked it so fast and never looked back.

So now we need to look back and fix.

#peace

**Comment by eschipul** [comment]
I would add - feel free to pound the project with 10 or 20 specific documentation issues and we have both volunteers in the community as well as people who work at our company who would love to tackle them. Doing pull requests on docs somehow seems less threatening than pull requests on code, but WOW DO WE NEED DOCS!

So to repeat myself, if in actionable chunks that the community can grab one by one then these are very very valid issues. Just not one issue as this is more of a year long project. And we can't manage that through on issue on github.

Thank you!
