### ISSUE TITLE
Cutomize more templates

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#391]
I use the Customize more templates button in the theme-editor to customize the dashboard template. It succesfullly downloaded the dasboard folder and the index.html but the changes I make to the file are not showing in the website.

**Comment by jennyq** [comment]
Most likely it is caused by django template cached loader. https://github.com/tendenci/tendenci/blob/master/tendenci/settings.py#L167. We might disable it. But for now, please restart your site.

**Comment by eschipul** [comment]
For performance reasons we need to cache the templates. Currently there are times you need to "clear cache" on the tendenci menu at the top under "apps" to have your updates visible. Alternatively you can turn off django template cached loader during dev as Jenny suggested. 

I typically restart the tendenci service with a bash shortcut because I'm lazy like that.

Still, I think all of us are definitely open to other ideas of a better way to optimize. To make things more intuitive, fast loading, and also easy on developers. Developers are in fact the first audience. And every developer hates caching and proxy servers during dev as they slow us down.

Also, thank you for adding these issues and helping build the community @dco5 . Can't wait to see your site live if it isn't already!
