### ISSUE TITLE
Confusion around requirements

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#404]
Hi,
I just realised that having followed the install instructions i'm using requirements/dev.txt whenever i do package changes. Looking in the file i see it just sources common and is missing several entries in requirements/prod.txt.

Should the documentation refer to requirements.txt in the top level rather than requirements/dev.txt?

(I don't see a reason to have 4 files at all, i'm assuming its to fit a pip/python coding convention though).

**Comment by eschipul** [comment]
@goetzk in previous versions of django you had to have a "requirements.txt" file in the root of the project. So that is a legacy thing.

Given you shouldn't need (at least in theory) to have things like the django-debug-toolbar installed in your production apps then theory went

/requirements.txt
- called /conf/ (text files) or called /requirements/(text files)

we copied the brilliant Rebecca Caktus work and used the /conf/ naming convention. And then flipped it. And now as you have observed we have an illogical result.

Temp solution - I usually install
pip install -r requirements.txt
pip install -r conf/dev.txt

Lastly, we also need to constrain them to be app >6<7 as a lot changed between 5, 6 and 7. Don't want to break everything in the wild that we don't don't about. 

Anyway, we've got some clean up to do on that. I'll add another issue after checking if one exists. I'll leave this one closed as it it titled on invoices. 

It is hard to correct now as all lives sites call tendenci-project-template once and after that you have to manually update your requirements files. Sorry! But I can at least get a clean example out there for everyone. That and we also have to remove all of the "7.zip" references which are there only to avoid breaking 5.x. Committees and videos for example are used pretty much everywhere so we're debating just moving those into core apps and avoiding the problem all together for at least some dependencies.

I'm not sure I explained this well. I'm very open to suggestions as I can see the problem, just not a quick fix that isn't a short cut that will just burn us again in the future. Once for all time and such.

**Comment by eschipul** [comment]
there is a deep irony btw that this is issue number "404". 

Oh I crack myself up. #uuuugh

**Comment by goetzk** [comment]
Finding The Right Solution is definitely the right way forward. I think i have the project branch cloned locally but haven't really looked at it.

**Comment by eschipul** [comment]
Tendenci requirements files are installed in three places.
1) setup.py on initial build
2) from the https://github.com/tendenci/tendenci-project-template repo but these can't be updated once installed
3) By people hitting errors and manually installing missed dependencies

This causes a number of problems from artificially inflating pypi downloads to errors on install that have to be debugged preventing adoption of software that should be easy to install.

Proposed solution (requesting comments!)

Option 1
1) move setup.py dependencies into /requirements/tendenci.txt and also replace this file on every --upgrade
2) keep the django standard of /prod.txt /dev.txt /common.txt but with the addition of the tendenci.txt file

Option 2
1) move setup.py dependencies into /requirements/common.txt and update this on every --upgrade
2) keep the django standard of /prod.txt /dev.txt but make sure people know on upgrade that common.txt WILL be overwritten.

On option 1 - that is non-standard django
On option 2 - that is standard django but could burn a developer who extends tendenci by adding things in common.txt and then that file gets blown out and replaced on every upgrade

Suggestions?

**Comment by goetzk** [comment]
I wonder if there is a variant on option two that can be used in conjunction with some documentation explaining the new system.

Off the top of my head an empty local_depends.txt is shipped but then not upgraded again (as the files are currently) which is sourced from requirements.txt. The local administrator/developer could add their own entries to that and common.txt (I'd almost argue anything in the requirements directory) would behave as you have offered above.

This seems like a workable compromise (as long as the local file is shipped empty since pip can't handle non existent files being included); I don't know how this would be wrt existing python developer expectations though.

**Comment by eschipul** [comment]
Close
