### ISSUE TITLE
T7 Inability to View Membership Applications- Redirecting to A Page not found

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#424]
There appears to be a redirect in the core of T6 that is causing issues for the Membership app and an error in the "View App" Link in T7.

Whenever trying to view a membership app that has been created, I am redirected to memberships/applications/corp-pre-add/

example: when I attempt to view this application: http://example.tendenci.net/admin/memberships/membershipapp/1/ or direct the url to that membership application here(http://example.tendenci.net/memberships/applications/basic-membership-application)
I am redirected to http://example.tendenci.net/memberships/applications/corp-pre-add/

If I try to click "View Application"http://example.tendenci.net/admin/memberships/membershipapp/1/ I am redirected to http://example.com/memberships/applications/basic-membership-application/.

**Comment by bleven** [comment]
Thank you for logging this bschipul. The error is caused by selecting the check box for "Use for Corporate Individuals" in the membership application. If the box is unchecked the redirect goes away. 

The "Use for Corporate Individuals" box is checked as a default when you add a new membership application. 

We should update so that the  "Use for Corporate Individuals" is not checked as a default for membership applications
![useforcorporateindividuals](https://cloud.githubusercontent.com/assets/4460314/10249378/98ba5860-68ea-11e5-8b08-fcfb2f79f54f.png)
