### ISSUE TITLE
T7 Specific - "Add Category" link does not work in Jobs Module

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#433]
In T7, when trying to add a job, if you click the link to "Add Category"it does not go anywhere.

We should see a window pop up that allows us to add a new category.

**Comment by eschipul** [comment]
can you please add a link to the page where this happens? Admin or front end or where?

**Comment by bleven** [comment]
@eschipul @bschipul just tested and this issue seems to be resolved.

This issue was happening in www.example.com/jobs/add/ 
When you click the link to add a category a window does pop up now that allows you to add the category
![addcategory](https://cloud.githubusercontent.com/assets/4460314/10794873/0494eaee-7d65-11e5-8a35-fc31f1b51f79.png)
