### ISSUE TITLE
Feature Request: allow redirects to an alternate domain

### ISSUE THREAD

**Issue by eschipul** [tendenci/tendenci#452]
#### Add full domain and subpage referrals to redirects module /redirects/

Frequently someone needs to redirect something like (hypothetically)
https://community.tendenci.com  to  https://www.tendenci.com/forums
which is a different domain. And a subdirectory or subpage. There is a work-around by modifying your nginx file, but this should not be necessary.

Additionally is there a reason that /redirects/ can't be in the admin interface of django given only superusers or staff with permissions can add them?

**Comment by goetzk** [comment]
@jennyq @eschipul I've been asked about this issue but the other direction (example.org/forum -> forum.example.org). Is that covered by this ticket too?

**Comment by jennyq** [comment]
@goetzk, you should be able to do that redirect in the current redirects module. For example, you can add these two redirects:

    From URL: forum
    To URL: https://forum.example.org

    From URL: forum/[\w\-\/]+
    To URL: https://forum.example.org
    # check Uses Regular Expression checkbox

The first one is for /forum/, and the second one for the sub-pages under /forum/. 
But I'd suggest to do that kind of redirects in Nginx for the efficiency sake.

**Comment by jennyq** [comment]
@eschipul, this issue is very old, pretty sure it's not relevant to you anymore. Can it be closed?

Redirecting entire site to another domain is not something the Redirects module can do. Nginx can handle it very well. 

Regarding why not in admin interface, it's because it doesn't need to be superuser or staff, any user with the redirects permissions can do it.

**Comment by eschipul** [comment]
Yes. Closed.
