### ISSUE TITLE
Meaningless error message creating event

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#454]
Hi,
I'm trying to create an event via Events module. I've started getting an error "Start Date/Time should come after End Date/Time" which is nonsensical. I'm hoping whatever the message is trying to convey can be clarified so it gives some clue as to what the user can do to resolve the issue.

**Comment by goetzk** [comment]
![screen shot 2015-11-07 at 15 11 16](https://cloud.githubusercontent.com/assets/8732490/11013438/eb5e1e38-8561-11e5-9154-44b32e7ee435.png)

**Comment by eschipul** [comment]
Yup, that doesn't make much sense when viewed objectively. To add your event the issue is that it has two (2) start date times so it's saying the second one (value of 2016-10-11 if after the end date above of 2016 10 10.

But the labels pretty much suck and need to be clarified. Leaving this ticket open for that.

For your particular event match your start and end dates. They should be labelled to indicate early registration periods with different pricing for some event types. A rarely used "feature" which in this case makes no sense.

Anyway - please adjust your dates so you can add your event. And as I said - leaving this ticket open as a bug. Or feel free to do a pull request on the template to clarify the intention of the dates.

**Comment by goetzk** [comment]
Thanks! I've redone the dates and have been able to save the event.

**Comment by goetzk** [comment]
Adding another entry I just noticed another set of dates all the way down the bottom in the pricing section. if those are 'enabled' but different (wrong?) the same message can appear.

**Comment by jennyq** [comment]
This issue has been resolved a while ago https://github.com/tendenci/tendenci/commit/5607d9b26abb4fb4e13b41a8c2eaaf9296ceeb45 The confusion was due to the broken js which was introduced when bootstrap3 was applied.
