### ISSUE TITLE
Time and Dates in Events module aren't self explanitory

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#455]
Hi,
As shown in the following screenshot there are two end dates, one start date then one each of start/end date with a time.

![screen shot 2015-11-07 at 15 11 16](https://cloud.githubusercontent.com/assets/8732490/11013438/eb5e1e38-8561-11e5-9154-44b32e7ee435.png)

I'm making an educated guess that the last "Ends on" is when the repetition ends ; I'm not sure how the other four date/time entries relate to each other or the 'all day' button.

**Comment by eschipul** [comment]
I'll have to look at the code, but I'm betting that is the pre-reg period and the reg period mislabelled. But I'll have to get into the template or the view to figure out which is which. At this point I don't recall which just goes to show the importance of documentation and clear labels on forms. Uuuugh. 

Ticket remain open. Catching the bug - I am grateful and thank you!

**Comment by Screamingkiwi** [comment]
I'm wondering about this one too, any update?

**Comment by jennyq** [comment]
It is indeed confusing! From the code, it looks like the second set of Start Date and End Date is used when *All Day* is checked. Otherwise, it just uses the first set of Start Date/Time and End Date/Time. The javascript code is broken - it is supposed to show either Start Date/Time and End Date/Time(if All Day is *not* checked), or Start Date and End Date(if All Day is checked).

**Comment by jennyq** [comment]
This issue has been resolved. 5607d9b b9ea1f3
