### ISSUE TITLE
Unable to add page

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#456]
When trying to create a page I'm getting returned to the page creation page so presumably there is an error of some sort.

After expanding Category I see the following error which I'm assuming is meant to tell me what needs fixing - but doesn't because it is simply providing references to the django data structures not items on the page which can be fixed.

```
There were some problems in the form. Please review. Thanks!
App label - This field is required.
Model - This field is required.
Pk - This field is required.
```

![screen shot 2015-11-07 at 19 39 12](https://cloud.githubusercontent.com/assets/8732490/11014375/6f7a54fa-8587-11e5-8d88-2db450370317.png)

**Comment by eschipul** [comment]
This was a bug that has been fixed. https://www.example.com/pages/edit/259/ - you still need a category and subcategory, but the pop-up blocker in many browsers were preventing adding categories on the fly.

If you can't update to the latest release of Tendenci at this time (github master branch) then you can use a work-around by adding the page on the admin backend. Or use another browser and disable pop-up blockers. I had the exact same problem which is why I know it has been corrected.

For me on the support menu I'm test it on 
Current Version: 7.1.23

Closing the ticket, but if it reoccurs on 7.1.x

Check http://tendenci.readthedocs.org/en/latest/upgrade/upgrade-to-tendenci7.1.html  for more.
