### ISSUE TITLE
Upgrading tendenci 5 to 6

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#472]
The instructions say to follow this: https://github.com/tendenci/tendenci/blob/tendenci6/docs/source/installation/local.txt#L142

In here it says to do pip install tendenci. But it is obviously installing tendenci 7 not 6 when I do this. Is the upgrade from 5 to 6 and then from 6 to 7.1 obsolete now? If not then how to install tendenci 6? Why would not be able to do it directly from 5 to 7.1?

**Comment by jennyq** [comment]
Hi @dco5, the instructions for upgrading tendenci 5 to 6 is here https://tendenci.readthedocs.org/en/latest/upgrade/upgrade-to-tendenci6.html. The one you linked above is obsolete.

The reason you'd need to do two steps of migration, from 5 to 6 then 6 to 7.1, is because t6 has some database schema changes that t5 doesn't have, and t7 is switched from South to Django migration.

**Comment by eschipul** [comment]
@dco5 - did that work for you?

The t6 upgrade, again only necessary because of the change from South migrations to native Django migrations, has different files in the requirements.txt file in that branch.

https://github.com/tendenci/tendenci-project-template/blob/tendenci6/requirements/common.txt

Note branch is "tendenci6" 

This is just me double checking that Jenny's answer got you up and running with the upgrade? If not reach out to me directly and I can take a look with you. Definitely eager to have more folks on T7 and it adds things like forums for free so the clients like it.

Closing the issue but feel free to ping me back directly.
