### ISSUE TITLE
restart required after theme changes

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#476]
Hi,
On our instance  a full restart of tendenci is required after updating a theme through the web interface (without a restart no changes display). Is this a bug in our setup or is this an expected behaviour?
If the former, where would I start looking for clues?
 If the later is seems strange to support uploading and updating themes through the web then requiring an administrator to ssh in to make it apply.

**Comment by eschipul** [comment]
The current theming will soon be deprecated to eliminate the regular expression use in nginx and urls.py for speed.

The current restart is because the theming is so slow with caching on it doesn't reload. For us this means constantly stopping and starting docker containers which is ridiculous.  For non-docker sites then usually a full "stop" and "start" of nginx usually accomplishes the same thing.

The future is a sym link for "publishing a theme" so the folder structure is always the same and nginx doesn't have to pass the workload back to uwsgi or gunicorn (gunicorn=bad anyway). But doing that breaks the theme preview so we need an architectural meeting on how to make that construct work. 

Internally given our use of wildcards on domains I would like to see something as simple as
www.example.org ---- live site
preview1.example.org  ---- theme1 on site
preview2.example.org ----- theme2 on site
halloween.example.org  ----- annual halloween theme on site but only active the week of halloween

Mainly I want nginx to do what it does best without losing the logic in the templates. Our current system doesn't allow for this. It works great in the beginning and then spends a ton of useless processing power evaluating the current theme on every page load for the typical two years between clients updating their sites. A waste of time and money for both developers and servers.

Anyway that is the bigger picture. I'm closing this ticket as the real issue is the caching. We could use a help file on the best ways to clear cache. Personally I just use two browsers and incognito mode which covers most, but not all use cases.

If this doesn't fully answer your question please do reopen it. And thank you @goetzk for your continued valuable participation and input. You rock mate!

**Comment by eschipul** [comment]
As noted by @goetzk - this is resolved on issue #525

**Comment by goetzk** [comment]
Cross referencing: #391 ; #387 .
