### ISSUE TITLE
Registration Pricing Options Confusing

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#483]
Under the tab for "Pricing" on events, there are fields that say, "Start Date/Time" "End Date/Time".

If no pricing is being used for the event, the fields control when people can register for an event.

This is rather confusing for a user setting up an event. 

Outlining One Possible Path to improving the usability:

Could we create an option on the Registration tab to select registration "Start" and "End" dates that are separate from pricing? 
Ideally then the pricing would default to the same dates as registration and  be hidden by default with a link under underneath "Change dates this price is available?". Clicking this link would pop open the start end date fields. 

Any other suggestions that would help make this area more intuitive welcome!

**Comment by Screamingkiwi** [comment]
Hi, can you create a  setting for a fixed date before the event eg 28 days, 90 days prior to the event starting.

**Comment by dco5** [comment]
The way it was set-up in T5 was perfect. I never had a complain from the users when creating an event. Now with T7 they say it is too confusing and hard to create events. Also a lot of menus have been hiding and not visible at first glance like before. People need to have everything at a glance, as cool as it looks hiding things with slides and accordions are not intuitive and people get frustrated if they can not find it in 5 seconds. Then they will take all the time in the world not to look for it but write an email complaining of how they can't figure out the website. The menus in T5, although not as appealing they were great.

**Comment by jennyq** [comment]
@bleven, I've fixed the Registration toggle for event add, and added some help text for the Start Date/Time and End Date/Time fields for pricings. Hope it can help reduce the confusion. https://www.tendenci.com/events/add/. I didn't add the "Start" and "End" dates under the Registration tabs as you suggested, because I'm afraid it would cause more confusion. At least one event pricing gets created for each event even if you don't specify anything in the Pricing name and description. The date time in the pricings determines when people can register an event. If we were to add the the "Start" and "End" dates under the Registration tab, what should we do if none of the pricings falls into the date time under the Registration tab? Let me know if this makes sense and if we still need to add those fields.

@Screamingkiwi, good thinking. But I'm not sure if we should add it right now. 

@dco5, great feedback! T7 has replaced old navs with the Mega menu. It would be great if you can add a new issue on how to improve the new Mega menu.
