### ISSUE TITLE
Search in help files shows incorrect result count

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#484]
For example, searching for entity
https://www.tendenci.com/help-files/search/?q=entity

This says 13 help files found, displays a two page 'next' navigation
button at the bottom of the page but only displays 2 results. (Tested in
Chrome and Safari).

(opened following a suggestion from @bleven)

**Comment by bleven** [comment]
Thank you for opening up ticket! not helpful if the helpfiles aren't available to you. will see if we can get someone on the team to poke into this

**Comment by eschipul** [comment]
Definite bug - but a good bug.

Philosophically I strongly agree with numerous double and triple checks on objects. For exactly this reason. The RO query is calling a broader security scope of who can see what. A problem with has_perm that I hate. So we have redundant security checks.

And on that note, i know people criticize me for that, but last time I checked servers were lower cost than developers so check once, twice, thrice. In this case it prevented a security issue but created confusion. Definite bug to fix but three cheers to the developer who implemented the double checks! Checking security over and over is truly PROFESSIONAL GRADE imho. 

Another one left open, but lower priority as it is superusers who will see this mostly instead of end users. Pull requests are welcome. Just keep the redundancy in the security checks please. Or add a third or fourth check. It's a big deal.

**Comment by jennyq** [comment]
We recently did an update for the version of Whoosh in the requirements.txt, which I believe fixed the issue. Closing it as the issue is gone now.
