### ISSUE TITLE
html5lib: cannot import name inputstream

### ISSUE THREAD

**Issue by gccfla** [tendenci/tendenci#505]
In between successfully bringing up Tendenci in a python virtual environment and trying to actually deploy in an Alpine-based container, html5lib changed.

Over at html5lib, they use Zeno-style versioning.  The working configuration installed html5lib version 0.9999999; the broken one installed 0.999999999 (with more nines to make it better!).  In seven-nines, we have inputstream.py; in the latter nine-nines version it's _inputstream.py, and thus I see:

    `A server error occurred.  Please contact the administrator.`

accompanied by this backtrace: [bt.txt](https://github.com/tendenci/tendenci/files/367881/bt.txt)

I wise programmer once told me the way to debug a program was to find the part that isn't working and remove it.  I'm not sure this advice works for the Tendenci/Django behemoth, or at least I'm not smart enough to apply it.

I would appreciate your guidance.

**Comment by jennyq** [comment]
@gccfla,

Thank you for reporting the error!

I've pushed out a fix https://github.com/tendenci/tendenci/commit/79613db71c0420d153c8004a9f9130625e434ee5. Please pull.

To debug this type of errors, the best starting point is to examine the full traceback of the error. It can help you to find where the problem is. In this case, it's one dependency breaking another dependency.
