### ISSUE TITLE
404 Errors Entire Installation -- Am I crazy?

### ISSUE THREAD

**Issue by wraith1821** [tendenci/tendenci#515]
Fresh Install of Ubuntu 16.04 LTS, followed installation documentation to the T.  Server runs and sees the homepage and can login, however, everything else is 404.

**Comment by eschipul** [comment]
You aren't crazy. Tendenci is still unacceptably hard to install. We are working on a docker make file and an AWS AMI version to simplify things. I apologize for the trouble.

That said, if the only error you were getting was a 404 then likely the issue was with the path or NGINX or uwsygi/gunicorn or similar. Not enough information to be actionable.

Feel free to create a new issue or post on stackoverflow if it is still a persistent issue. Closing the ticket for now and sorry for the delayed update.

Ed
