### ISSUE TITLE
Event Organizers Should get emails

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#518]
Hello, I have 2 different non-profits that are requesting that the event organizers get emails about registrations and payments for the event they are the organizing. The way the model is set up right now that is completely impossible to do. Even if is just adding a field to the model for the emails of the organizers, that would help a lot. Ideally when the event is being created there should be an option of selecting a members as organizers or adding the info of the organizer. 

I tried doing it as an addon, but I had to change too much of the core functionality and the model, and it would probably break with a future update.

**Comment by eschipul** [comment]
This is a great mod IMHO. Thinking....

Before determining a method of implementing it, may I ask what merchant provider they are using? I ask because there is other discussion going on about changing API integration method with authorize.net and/or stripe. If so it might be better integrated into that project.

?

**Comment by dco5** [comment]
For one we are using Stripe since it was a set-up, for the other one we are using Authorize.net since it was an old upgrade.

**Comment by jennyq** [comment]
A lot has changed since this issue was opened. If you want the payments go to different accounts, you can set up stripe connect and make the payments go to different stripe accounts https://tendenci.readthedocs.io/en/latest/topic-guides/payments.html#how-to-use-stripe-connect.

Instead of organizers getting emails, when editing an event, under the "Registration" tab, you can now specify an email address to receive the admin notices for the event.

![image](https://github.com/user-attachments/assets/c535d4db-98bb-4318-8f1c-c05f31ad0e08)
