### ISSUE TITLE
Setting the receive_mail field in /profiles/ doesn't work

### ISSUE THREAD

**Issue by jamesoflol** [tendenci/tendenci#520]
Issue present on our org's install, and I loaded up a clean brand new Tendenci to test.

Steps to reproduce:
- oursite.org/profiles/edit/1234
- Receive Email: Set to 'No'
- submit changes
- reload same edit page. field still says 'Yes'. (whereas the field in the database is actually set to 'No' which is the default

BTW, was it a conscious decision that the default for this field is False? I feel that the majority/default stance of an org member is 'yes I want to hear from you', which they can opt out of later.

Cheers
James

**Comment by goetzk** [comment]
Hi,
I've just tested this in a tendenci instance (7.1.35 iirc).

When I update the value via https://example.com/profiles/edit/10659/ I see my user objects direct mail value changing.
```
>>> Profile.objects.get(user=User.objects.get(email='karl@example.com')).__dict__['direct_mail']
True
>>> Profile.objects.get(user=User.objects.get(email='karl@example.com')).__dict__['direct_mail']
False
>>> Profile.objects.get(user=User.objects.get(email='karl@example.com')).__dict__['direct_mail']
True
>>> 
```

However the UI for '  Receive Email?' always displays yes. I think its because of this code in apps/profiles/forms.py (line 158)

```
    direct_mail =  forms.ChoiceField(initial=1, choices=((1, _('Yes')),(0, _('No')),))                                 
```

From what I gather this forces 'yes' to be the option displayed on each load.

I'm not entirely sure what the correct fix is but I suspect something like https://docs.djangoproject.com/en/1.8/ref/models/instances/#django.db.models.Model.get_FOO_display

**Comment by jennyq** [comment]
Thanks guys for pointing out the problem! The default value of direct_mail is False in model but it is set to True on Form, so I'll leave it as is.
