### ISSUE TITLE
Direct_mail field default is False

### ISSUE THREAD

**Issue by jamesoflol** [tendenci/tendenci#524]
Followup from issue #520 

Hey Jenny

Thanks for fixing the bug. It now "works" but I'd like to stress that I really feel that the default is incorrect.

I would really think that anyone who signs up with an org would want to hear from them by default. Opting out, rather than opting in, so to say. It may be confusing because I believe the field name is a bit odd and legacy - "direct_mail" is an odd name, but the field title in /profiles/edit is "Receive email".

Can we please change the default to True?

If not, what's the best way for me to change this just for our org?

Thanks
James

**Comment by eschipul** [comment]
The default should definitely be set to "True", and yes it is a legacy naming convention. However, in order for it to be "True", and this could be decided by looking at another field or even a new field, but the user has to confirm their email address before you can send email for the CAN SPAM Act.

In the case of active users they have by definition confirmed their email address when they registered on the site, so every active user should be set to True.

We just need to find a way for non-active users (newsletter subscribers who don't login but filled out a contact form for example) to confirm their email.

Any suggestions? And again "yes" on defaulting to "true" for any active user. I'm asking how to handle people who just fill out a contact form to sign up for the newsletter. Ideas on the work flow?

Also don't forget about "email blocks" which is a last resort way to block sending email of any kind to a particular email address. This was added because some people are crazy and add themselves and then complain, then do it over again, then complain. I can't fix crazy so email-blocks is the solution for that.

**Comment by jennyq** [comment]
The default value of the direct_mail field has been changed to True https://github.com/tendenci/tendenci/commit/bda0e66dd703739bafa61c0434fc991211c2feb2. 

However, I just checked and found that the `direct_mail` field is **not** being used - not for newsletters nor for other emails. In stead, the newsletter sending is using the field `is_newsletter_subscribed` https://github.com/tendenci/tendenci/blob/master/tendenci/apps/user_groups/models.py#L179. In that case, it doesn't matter whether the non-active users have the direct_mail set to True or False.

**Comment by jamesoflol** [comment]
Hi Ed.

Thanks for the reply. A few good points to mull over.

Just to be sure, AFAIK contact form fillers don't get made in to users at all, therefore they wouldn't get newsletters?

Interesting about the email blocks. Is this for if someone says "delete my account", but then signs up again?
