### ISSUE TITLE
Impersonation is no longer possible

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#527]
Hi,
I've seen Impersonation mentioned as a feature in older tendenci releases, e.g.
https://www.tendenci.com/articles/tendenci-update-version-5068/

This feature doesn't appear to work anymore; has it been deliberately removed or has it bitrotted? Alternatively a proper question is: Can users still be impersonated?

thanks,

**Comment by goetzk** [comment]
I've just been pointed to where impersonation can be performed:

- View a users profile
- In the admin bar look at 'Users' app configuration then under 'This User' choose 'Change Password'
- On that screen is 'Edit More options' dropdown
- 'Impersonate' is in that list.

Only problem seems to be that it isn't working correctly - at least on our install. Adding  ?_impersonate=usersname to various links still shows me the site using my staff+superuser account not the targets account.

**Comment by eschipul** [comment]
@goetzk - Karl - I had to kill impersonation even thought it was part of the original design goals on the rewrite. It was implemented in a way that was insecure given "all code WILL be copied and pasted." (also please excuse pseudocode style)

Tendenci loaded an anonymous user object on every page from version 0.01. Django did not, adding this back later (1.4? 1.8? Not sure.) Anyway, previously I didn't see the need for impersonation outside of the users module so those methods were called similar to 

(all pages got "tpages, email, eventlog, user" objects instantiated before load. From there an example would be:

```
set usercurrent = new users
usercurrent.userid = 5432 
currentuser.pop(conn, user, *kwargs) 
``` 

- managed populating the "currentuser" object taking into account the permissions of the primary "user" object passed in byref.

inside of methods in class - sub-methods would look at security from the objects perspective instead of the users perspective for speed. Servers were much slower. Not all apps could be loaded into memory on all pages so it was untennable to have a global "user.has_perm" structure. We reversed it.

```
set article = new articles
article.articleid = 123
article.viewpop(conn, user, *kwargs)
```
  ... inside class functions like "if me.allowviewby(conn, user, *kwargs) then me.viewpop(conn, user, *kwargs) etc" 

That would populate object using only the data in that user object. Very fast.

My goal of impersonation was to use two user objects at all times. Unfortunately I didn't articulate this well and the user object's asociated profile object was reloaded with the impersonated users data. That broke the security because now the main "user" on the page effectively IS the impersonated user and not an emulation. A security nightmare - here is why.

Impersonation as implemented would break all logging as a hacker gaining access would BECOME that other user and all eventlogs would reflect that the other person had made the change. (Eventlogs should NOT be relational at all as well but I'll have to fix that another day - they are for auditing and should always be a snapshot - never to be changed)

Back to emulation - the intent. In preload - two empty user objects initially on all pages - get primary user in "user") then

```
set article = new articles
article.articleid = 123

if user.isemulating(user2) then
    article.allowviewby(user, *kwargs)
        article.allowviewby(user2, *kwargs) 
```

This is acceptable because if "user" doesn't have permission then they can't emulate someone else who might have permission to the object and elevate their rights in that manner. (think Django SITES and shared auth...)

I want emulation. However the hooks are not in place to keep two distinct and discreet user objects simultaneously and without that it can't ever be properly secured.

**Comment by goetzk** [comment]
On 10/1/17 08:56, Ed Schipul wrote:
> @goetzk <https://github.com/goetzk> - Karl - I had to kill impersonation
> even thought it was part of the original design goals on the rewrite. It
> was implemented in a way that was insecure given "all code WILL be
> copied and pasted." (also please excuse pseudocode style)

[explanation]
That clears things up, thanks! Its a pity there is no impersonation but
it is something we can live without and a secure implementation is
definitely preferable to a broken one.

thanks,
kk

**Comment by eschipul** [comment]
@goetzk I haven't given up on it, it just requires first fixing eventlogs to be actual logs while still allowing eventlog reports. Then working through the objects one by one. So I keep kicking myself for not catching that in the early code reviews. Completely my fault. We'll get it back as if logged and implemented securely it would really speed up helping the end users.

Thank you again @goetzk for the great questions. Your thoughts are exactly correct - we'll figure out a secure way to do this down the road.

Closing this issue for now.
