### ISSUE TITLE
Private URL Events

### ISSUE THREAD

**Issue by JustinLewisSMA** [tendenci/tendenci#542]
When an event is marked as "Enable Private URL", it should still show in the following urls if you are an Administrator, otherwise Administrators are forced to remember the ID:
https://www.tendenci.com/events/search/
https://www.tendenci.com/events/month/

Unless there's another, (less intuitive) way to find them!

**Comment by jennyq** [comment]
@JustinLewisSMA, There IS a way to find them (yes, less intuitive). You can always find the Private URL under the "Enable Private URL" on the event edit page.

**Comment by JustinLewisSMA** [comment]
I think I was unclear. You can't find the Event Edit page unless you know the Event ID after the event is set as private.

Said another way, How do you find an event after it's marked private?

**Comment by jennyq** [comment]
Oh, I see now. I think it's a fair request.

**Comment by eschipul** [comment]
Yes, good functionality but I'm not comfortable with the implementation because it breaks with convention. If I click a URL that someone sends me it is reasonable to think that I might be seeing extra content as a super_user, but that the "core data" is similar.

To show private events here:
https://www.tendenci.com/events/search/
https://www.tendenci.com/events/month/

would potentially result in phone calls like "look at the last event on this page https://www.tendenci.com/events/search/ " and we would be looking at different content. The last event would differ is my point if there was a private event above with pagination turned on.

A template_tag that changed the URL would overcome that objection, or maybe we're over-engineering this and just need a page like:
https://www.tendenci.com/events/search/private/

I'd add that it bothers me greatly that we've hidden the IDs so well developers can't work efficiently. Users are awesome at ignoring things, so the ID should be visible to everyone IMHO on all pages even if the slug doesn't include it. What is the harm of a footer with the ID and a timestampe etc? None imho.

Anyway, thoughts on https://www.tendenci.com/events/search/private/ or maybe in the admin backend (another area that needs love and should show the ID in EVERY LIST VIEW.)

?

**Comment by JustinLewisSMA** [comment]
Having a different pagination from users when logged in as a super user is less of an issue than forgetting what the ID is for your private event and having to incrementally go through them until you find it! Simple communication "what is the date of the event you're talking about?" fixes this issue.

I think that /events/search/private is a great solution as well (assuming it only shows to super users!) and it's linked somewhere in the admin so that it can be located by staff.

**Comment by jennyq** [comment]
@JustinLewisSMA, 

An events list page has been added at the admin backend, which includes events with private URL enabled. e.g. https://www.yoursite.com/admin/events/event/. 

To get a list of private events, just click Filter (By Enable Private URL) -> Select "Yes". 

Does that work for you?

**Comment by JustinLewisSMA** [comment]
@jennyq Fantastic, thank you!
