### ISSUE TITLE
Email bounced when auto-fill the second email address field at the Contact Us form 

### ISSUE THREAD

**Issue by mfmjw** [tendenci/tendenci#549]
The email To field is set to No-Reply Address and caused the email to be bounced.
The issue can be resolved by re-typing the second email address.
It would be a good to have feature to detect that the second email address is input via keystroke and not auto-filled.

**Comment by FourthEstate** [comment]
+1

**Comment by eschipul** [comment]
This is a browser reflex that personally drives me crazy. Hence the odd-names of the email and confirm email form fields on reg because browser fill causes lockout. 

If you have a more elegant way of handling it besides ducking away from the common names for pw and pwconf fields then please let us know. Gut using a script to autofill the second email input defeats the purpose, right?

I hat spammers. It's frustrating that we have to deal with this (all of us, yourself included for sure.) I'm just unsure of a systemic solution that doesn't break the goal of having double entry?

Closing the ticket for now. Reopen if it is still an issue please.

Thanks - Ed
