### ISSUE TITLE
BUG:  Corporate membership only creates one membership application link

### ISSUE THREAD

**Issue by FourthEstate** [tendenci/tendenci#560]
We are seeing an issue where only one membership form URL link is being created despite multiple forms and corporate membership types being setup.  

The Corporate membership module only allows us to create one membership application.  However the ability to create individual membership applications based on the type of Corporate Member would be immensely useful.

For example we have News Organization members but also other types of organizations such as associations, colleges/universities etc that we want to have unique memberships types and applications for. @

**Comment by casbeebc** [comment]
This seems to be a feature that needs to be  implemented rather than a bug:


[line 1312: apps/corporate_memberships/models.py](https://github.com/tendenci/tendenci/blob/master/tendenci/apps/corporate_memberships/models.py#L1312)
`
def is_current(self):
"""
Check if this app is the current app.
Corporate memberships do not support multiple apps.
"""
...
def application_form_link(self):
        if self.is_current():
            return '<a href="%s">%s</a>' % (reverse('corpmembership.add'),
                                            self.slug)
        return '--'
`

**Comment by FourthEstate** [comment]
The this MUST be a feature.

**Comment by eschipul** [comment]
Some background to help us all think through this:

1) Corp membership evolved from companies buying a membership for x number of employees. (e.g. 10 for silver level, 20 for gold, 50 individuals for platinum or whatever the org called it.)

2) Corp memberships were quickly abused by individuals within the organization signing up under their umbrella. So a large org like Yahoo might buy a membership which included 10 members and was restricted by email domain (e.g. @yahoo.com). Then a VP would go to join as an individual under that corp membership and get denied because the 10 slots were filled. This is a problem.

3) One person "owns" the corporate membership. If they leave an organization then the renewal notices don't arrive when it expires. The cron job will therefore expire the 10 individual memberships (as it should) as part of the corporate membership.

4) Further restricting corporate memberships by domain name is a challenge for organizations such as yours, or a photography organization, where everyone is a legit member but that can't be controlled by checking if everyone is in the same email domain.

While not a fan of the "slippery slope" fallacy/rhetoric... on this issue it does apply. The owner of a corporate membership frequently does not and should not have admin rights effectively over individuals who join under that corporate membership. If your company sets up a benefit for me, it does not mean the owner of the corporate membership should be able to edit my user profile. That is a security problem.

Question - Corp Membership is the glue that holds individual applications together. I'm unclear why a corp membership wouldn't work as is with different individual membership types below it? What am I missing?

**Comment by FourthEstate** [comment]
The issue with this is not the Sub Accounts under corporate membership.  

This is a marketing issue.  In much the same manner as the Individual member types have a custom application form it should work the same way for organizational/corporate applications

The issue is that although I am creating unique membership applications for corporate/organizational types that the corresponding link isn't being created them in the system.

![screen shot 2017-04-12 at 4 43 39 pm](https://cloud.githubusercontent.com/assets/23258672/24978712/a5e18ea6-1f9f-11e7-8c7a-c5cc38a69f77.png)

**Comment by eschipul** [comment]
Ahhh, OK, I think I get it now. Let me test on a fresh install as my dev environment needs to be rebuilt regardless.

**Comment by FourthEstate** [comment]
Thanks it would be phenomenal to get this fixed quickly.  It prevents us from using the AMS and has had us looking at alternatives.
