### ISSUE TITLE
Feature Request: Monthly payment plan for membership dues

### ISSUE THREAD

**Issue by FourthEstate** [tendenci/tendenci#566]
Having the ability to allow the member to decide to split the membership dues into a set number of payments  is extremely useful for associations. Many organizations do this but it becomes a human capital intensive process.  

The feature would allow the Association to be able to turn on a Monthly payment plan if desired. Have it carry a "admin fee" if selected.
The member, when choosing the payment or checking out would have the option of make one payment for the membership as they do so now, or use the payment plan.

**Comment by eschipul** [comment]
have you looked at recurring payments? Currently being built out for authorize.net and working on the UX but it is functional. The goal is to improve the flow of recurring memberships and then expand to Stripe and the other merchant providers that support it.

Then the request becomes one of "monthly memberships" that recur 12 times. Same functionality, correct?

**Comment by FourthEstate** [comment]
That's certainly one "work around" but in reality the solution needs to be a more elegant solution that solves the actual problem for the organization.

Also organizations may not want to break up payments into 12 months.  They may want some different number.

**Comment by bdruth** [comment]
Any updates on this? I'm happy to read that Stripe integration is "in the plan" - though it seems like it's been a long time and this still isn't available. Where would I start to add this? The Stripe API seems brilliantly simple and you're already handling tokens, which is the hardest bit, it seems.

**Comment by eschipul** [comment]
Short version @bdruth @FourthEstate - you are both correct.

Longer version - Stripe integration is in place. Info on setting it up for your site for one time payments is here:
https://www.tendenci.com/help-files/configure-online-payments-merchant-provider-tendenci/

For example www.tendenci.com/py/ processes one time payments using the stripe API. In other words - we are using Stripe Payment Processing ourselves and have a strong incentive to get this working for everyone. 

BUT.....

**NOTE: Before I say anything else - clients will always have the option to set up their own providers as there are laws in various countries that require this. This will NOT change.**

With Stripe - the challenging part is to get better prices for our clients, open source or not, right? If Stripe can deliver a 1.9% reduction in rate from middle men who don't actually do anything like F I R S T data, then we need to have the clients (open source or hosted in the Tendenci Cloud) "bundled". This would more than give us the volume that Stripe is looking for to achieve a better rate. To achieve that, from talking to Lauren at Stripe in the last two weeks, clients would need to be on the "connect" product. 

This would also potentially provide another small revenue stream to fund the software of maybe 0.5%. In theory it would save clients between 1.4 up to 5% for smaller new NGOs and still generate funds for Tendenci to reinvest in the software.  

My contact at Stripe is Lauren Dai https://www.linkedin.com/in/laurendai/ and she's been super helpful. We just haven't had the resources to program to the stripe "connect"  product for recurring revenue.

I do know C h a r g i f y radically increased our own recurring monthly fees and our clients have a great credit track record (in other words we are low risk, right?). Hence getting off of Charify and running our own business recurring payments via stripe is a priority.

Lately I'm spending more of my time with NGINX/OSSEC/Kibana/ELK-Stack/IDS/IPS/Endpoints than I am moving the ball forward. I find this frustrating. But associations are being targeted so that is my current priority - to protect.

Hit us up with ideas or resources. Maybe someone at Stripe who likes open source can help? I'm truly open and asking for help. We're kind of a small operation behind a much larger movement to free governance from proprietary constraints.

**Comment by bdruth** [comment]
So - we have Stripe integrated - that was super simple, as you indicated in the link you provided. But - that's only for one-time payments. I'm happy to help get recurring payments setup w/ Stripe as I'm a software engineer and I'm volunteering my time for the charity my wife is leading. From looking at the recurring_payments code, however, it seems like this is pretty far afield from how Stripe works? Looks like authorize.net requires ongoing scheduled activity from the system to work whereas Stripe manages all that and just invokes webhooks when payments are processed. Maybe I'm misunderstanding the current implementation, but if I can get a crash course on "start here" and "go here" - as far as getting something working and then where to integrate it into the memberships module, that would be great. I've never written a django app, but I've messed with Python from time-to-time, so it's not completely foreign.

**Comment by jennyq** [comment]
Hi @bdruth, the recurring payments and membership auto renew with stripe are already in place. We didn't use webhooks for two reasons: 1) The webhooks were not available when the recurring payments module was initially built with authorize.net many years ago; 2) We can have better control for memberships auto renew. For example, if the expiration method changes for a membership type, with webhooks, all subscriptions at stripe would need to be updated. 

To check out the memberships auto renew, follow the instruction to set up stripe https://www.tendenci.com/help-files/configure-online-payments-merchant-provider-tendenci/, have the Recurring Payments enabled /settings/module/recurring_payments/#id_enabled, and turn on the "Allow Auto Renewal" setting /settings/module/memberships/#id_autorenew . Then on your memberships app, a checkbox "Allow Auto Renew" will appear. At stripe, a customer is created when someone opted in.

As for "to split the membership dues into a set number of payments", it's currently not in place. I'm unsure how to best implement this. Maybe it can utilize stripe subscriptions.

**Comment by bdruth** [comment]
I'm trying this now - as far as my need - I'm good with this - I can setup a 2nd membership type that is X/12 w/ a 1 month renewal instead of X w/ a 1 yr renewal.

**Comment by bdruth** [comment]
I don't see /settings/module/memberships/#id_autorenew ... did this come after 7.4.0? If so ... how do I get that? I'm just running from pip install tendenci.

**Comment by bdruth** [comment]
nvm, I see 7.4.1 is out there now ;)

**Comment by bdruth** [comment]
Well, crap. Looks like dj-pagination just broke you :( They released 2.3.1 today, which is the latest version in ``pip`` and it depends on django-2 from what I can tell in the backtrace.
```
Collecting dj-pagination>=2.2.0 (from tendenci==7.4.0)
  Downloading dj-pagination-2.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ymMFJL/dj-pagination/setup.py", line 87, in <module>
        include_package_data=True,
      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 257, in run_setup
        raise
      File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 170, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 145, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-IgluAK/Django-2.0/setup.py", line 32, in <module>

      File "/tmp/easy_install-IgluAK/Django-2.0/django/__init__.py", line 1, in <module>
      File "/tmp/easy_install-IgluAK/Django-2.0/django/utils/version.py", line 61, in <module>
    AttributeError: 'module' object has no attribute 'lru_cache'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ymMFJL/dj-pagination/
```

**Comment by bdruth** [comment]
fwiw, dj-pagination f'd up their release - see https://github.com/pydanny/dj-pagination/issues/15#issuecomment-354525282. I've managed to work around it by using a requirements.txt that I install first, followed by tendenci, e.g.:
> requirements.txt
```
-e git+https://github.com/jmichalicek/dj-pagination@condition-dependencies#egg=dj-pagination
```
> commands
```
RUN pip install --no-deps -r requirements.txt
RUN pip install tendenci==7.4.1
```

**Comment by bdruth** [comment]
also, fwiw - previous versions of tendenci fail to install now, too - I'm guessing the django 2 release triggered all this fun, but I guess I'm not 100% sure of it.

**Comment by BenSturmfels** [comment]
Just to bring this one back on track, now that Tendenci supports auto-renew with Stripe, I believe the remaining component is having 12 monthly payments against a single membership, rather than 12 memberships. Is that what you're getting at @FourthEstate?

**Comment by goetzk** [comment]
@BenSturmfels 
I can't speak for @FourthEstate , but that is what I want from this ticket, and why I am following it :)
kk
