### ISSUE TITLE
Support for invoice references

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#570]
Hi,
When requesting members pay by EFT they need a way to be able to identify their payments. Since I don't see a way to do this in tendenci at the moment (we're a little behind on version .47) I added this to view.html and print_view.html.

As suggested in http://stackoverflow.com/a/6052784 , I'm using slice instead of truncatechars. The reason is that truncatechars adds '...' to a string it truncates.
    
    https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#truncatechars
    https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#slice

I've limited members names to 13 characters to ensure our references stay within the 18 characters required of Australian banks.

    https://community.commbank.com.au/t5/NetBank/Transaction-description-18-character-limit/td-p/64686

+      <li>Payment reference: {% if invoice.bill_to_last_name %}{{ invoice.bill_to_last_name|slice:":13" }}{% endif %}{% if not invoice.bill_to_last_name and invoice.bill_to_first_name %}{{ invoice.bill_to_first_name|slice:":13" }}{% endif %}{{ invoice.id }}</li>

Would you like me to do this up as some sort of documentation that could be added? if so, where should I put it?

thanks,

**Comment by FourthEstate** [comment]
+1

**Comment by goetzk** [comment]
It also occurs to me that this would be useful to have in the invoice class/objects as it would allow accessing it in Other Places (TM).
I haven't looked at how hard it would be to implement but I suspect not very - if this is a desirable thing I'll try and do up a merge request.

**Comment by jennyq** [comment]
Does this reference need to be unique? Why don't you just use the invoice ID which is a unique field? The invoice ID shows on the invoice view as "Invoice #".

**Comment by goetzk** [comment]
The reason it was brought to me is that EFT payments need a reference so they can be identified and the member marked as having paid. its /possible/ to use invoice ID but that might be indistinguishable from the a member(ship) number in small systems. A member specific identifier + invoice id makes things easier for everyone to keep track of.

**Comment by eschipul** [comment]
True @goetzk but if we move away from the invoice_id then we are diverging from a practice followed by all payments. For example to generate a report of EFT funds vs Credit cards would get much more complicated from an SQL perspective. Invoice ID is the glue between everything - which is why an invoice goes from "estimate" to "tendered" when the user makes a payment.

While we are not quite ready to bring forward, and honestly I don't want to, the Unified Chart of Accounts, it is important that there is an underlying GL. The links between the modules and payments all flow through invoiceid, even if abandoned "estimate" or if "pay by check" requiring a duplicate entry in accounts payable for some clients.

All of that said... I see no problem passing over an ADDITIONAL variable to help accountants reconcile all of this. We use authorize.net and f***d**** and the fact that not even the dates line up makes reconciliation a pain. So if your pull request and logic preserves the sanctity of the invoice_id being the "glue" and the EFT guid/id/etc being additional info for reconciliation, then I see no problem with it. *I like it.* Just never to the exclusion of the invoice_id.

Did I understand that correctly? Or am I way off base? I respect your efforts to make EFT easier so that the community can lower costs and put that money towards their cause. I think we're on the same page with that part. I'm just not sure I understand the proposed implementation?

This also makes me wonder if our team shouldn't set up a staging server again. We run very lean over here out of necessity so typically it's dev to  prod. Reckless perhaps. I'm open to ideas on that as well. 

Ed

**Comment by goetzk** [comment]
I thought I replied to this 6 days ago but my email clearly hasn't made it here. Below is a paste from my mail client.

On 30/6/17 14:49, Ed Schipul wrote:
> True @goetzk  but if we move away from the
> invoice_id then we are diverging from a practice followed by all
> payments. For example to generate a report of EFT funds vs Credit cards
> would get much more complicated from an SQL perspective. Invoice ID is
> the glue between everything - which is why an invoice goes from
> "estimate" to "tendered" when the user makes a payment.
>
> While we are not quite ready to bring forward, and honestly I don't want
> to, the Unified Chart of Accounts, it is important that there is an
> underlying GL. The links between the modules and payments all flow
> through invoiceid, even if abandoned "estimate" or if "pay by check"
> requiring a duplicate entry in accounts payable for some clients.

I'm not familiar with Unified Chart of Accounts nor what you mean by GL.

I did find the Tendenci blog but the linked page is now a 404 (FYI I guess).
https://blog.tendenci.com/ucoa-unified-chart-of-accounts-for-npos/
http://nccs.urban.org/projects/ucoa.cfm

> All of that said... I see no problem passing over an ADDITIONAL variable
> to help accountants reconcile all of this. We use authorize.net and
> f/*d*/* and the fact that not even the dates line up makes
> reconciliation a pain. So if your pull request and logic preserves the
> sanctity of the invoice_id being the "glue" and the EFT guid/id/etc
> being additional info for reconciliation, then I see no problem with it.

Thinking about it further, if changing the invoice model it would just
need a method for eft_reference which does what I did in the template.

> /I like it./ Just never to the exclusion of the invoice_id.
> Did I understand that correctly? Or am I way off base? I respect your
> efforts to make EFT easier so that the community can lower costs and put
> that money towards their cause. I think we're on the same page with that
> part. I'm just not sure I understand the proposed implementation?

I'm definitely not proposing invoice id is removed. Hopefully the
following explanation clears things up.

Our invoices start with

> Invoice #	200
> Invoice For	Optional Organisation
> Karl Goetz (Name of member being paid for)
> 
> Member address, invoice date, invoice status and so on.

It finishes with the following EFT payment info:

> *Bank account*
> Name: Organisation being paid
> BSB: xxx xxx
> Acct: 12345678
> Payment reference: Goetz200

Here the invoice number is included, as is the payment reference which
is obviously not a membership number or other random string.

> This also makes me wonder if our team shouldn't set up a staging server
> again. We run very lean over here out of necessity so typically it's dev
> to prod. Reckless perhaps. I'm open to ideas on that as well.

If the testsuite is comprehensive it may not be needed, but we've
encountered a few things where we wondered how it could have made it to
a release.
Testing isn't free of course, its a trade off in perceived benefit.
