### ISSUE TITLE
Add at code level to correct file naming convention

### ISSUE THREAD

**Issue by ediaz1** [tendenci/tendenci#597]
Naming conventions of files containing dots (never more than one dot in a file name), underscores, spaces, and uppercase. This conflicts with the protocols initial standards and doesn't do well in search. File names need to replace dots, underscores, and spaces with dashes. And change all letter casing to lowercase. 

Here are a few ideas for this:

1. Detect the file when uploaded with these characters and prevent it from going through with a warning message to the user to update the file name.
2. Automate a way to update the file name when the file gets uploaded.

**Comment by ediaz1** [comment]
[9:31 AM] Ed Schipul: we need a github issue added to force all file uploads to be all lowercase, replace spaces and underscores, or dots, to be dashes with only one dot allowed prior to the file extension.
[9:35 AM] Ed Schipul: So “blah BLAH Hah.5.7.8.jpeg” should be renamed “blah-blah-hah-5-7-8.jpeg”

**Comment by ediaz1** [comment]
Would any of these be helpful to renaming files that contain uppercase, underscores, spaces, or extra dots:

1. Auto rename file upload with file validator: https://djangosnippets.org/snippets/10565/
2. Configure file: https://www.tinymce.com/docs/enterprise/server/configure/#creatingaconfigurationfile

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/9a19949d9682c55f893a0e7aa41ecd80bc32b41d

**Comment by PaulSD** [comment]
I know spaces in filenames are a problem due to https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1 ... and that Google recommends dashes over underscores in URLs (https://support.google.com/webmasters/answer/76329?hl=en), although Google has never actually explained why they recommend that or if there are actually any consequences to using underscores (Google employees have stated that it is not worth replacing underscores in existing URLs with dashes, for whatever that is worth), and most other search engines have publicly stated that they handle dashes and underscores the same.

However, multiple dots and uppercase letters do not conflict with any protocols or have any impact on searches that I am aware of.  Multiple dots may be a problem if files are stored on an ancient FAT16 filesystem, but in that case, you also need to truncate the filename to the old 8.3 format ... they are not a problem on any modern filesystem that I am aware of.

What problems do multiple dots and uppercase letters cause?

**Comment by jennyq** [comment]
Regarding "multiple dots and uppercase letters", I think it's mainly for best practices. The dots carry some special meaning in the unix file systems (i.e., `./` for current directory, `../` for parent directory). As for the uppercase letters, PostgresSQL is case-sensitive, it'd be good for search if file names are all in lowcase.

**Comment by ediaz1** [comment]
"Block the upload of any file with a comma or two consecutive dots in it. e.g. test,test.jpg (FAIL) and test..test.jpg (FAIL). Not at a javascript level but at a server level. JS can be added as well but it must be blocked fundamentally at the server."
