### ISSUE TITLE
Migrate from Django 1.8 to 1.11

### ISSUE THREAD

**Issue by PaulSD** [tendenci/tendenci#613]
Support for Django 1.8 will end in April 2018.

**Comment by AdamBark** [comment]
I'm not really sure what the best way to communicate with the project is but this seems relevant. I started a branch to do this migration and have Django 1.9 working for migrations and it passes 'test' https://github.com/AdamBark/tendenci/tree/django-upgrade
I'm not sure everything I've done so far is exactly right but hopefully some of it will be useful. I've started working on 1.10 and I'll comment again when that's working and pushed to github.

**Comment by eschipul** [comment]
Thank you again - we're sometimes get caught up in client work when we want to be working with the open source community more. There is of course no difference in the code - the open source version IS the exact same version our hosted clients use. So thank you again.

As for a major change like the move to 1.10, i believe it definitely warrants a new branch. I'm a big proponent of commenting code, moving fast, but we've got a lot of changes ahead. Everything needs to be centered on ubuntu 16.04 and bootstrap and SSL without exception. Internally we use dockers. but our makefile keeps getting outdated (e.g. docker-ce just switched to overlayfs2 from overlayfs and that isn't a small thing.)

@AdamBark @PaulSD thank you both. we're literally a tiny team trying to balance an elephant on the top of a needle. Your help is SOOO appreciated. My vote is definitely a new branch for 1.10 on 16.04 LTS. 

That said - I always seek the input of our project lead @jennyq as she is quite brilliant and I may be mistaken. Jenny, what are your thoughts?

**Comment by goetzk** [comment]
On 5/3/18 16:24, Ed Schipul wrote:

> As for a major change like the move to 1.10, I believe it definitely
> warrants a new branch. I'm a big proponent of commenting code, moving

In that case, could I suggest the branch be for the 1.11 upgrade and do
it all in one hit?

kk

**Comment by AdamBark** [comment]
My branch is called django-upgrade and I was planning, roughly, one commit per Django version with a final destination of 1.11 as 2.x requires python 3

**Comment by jennyq** [comment]
Hi @AdamBark, thanks for taking the lead on upgrading to django 1.11. I'll make a new branch so that your PRs can be merged to. But before I do that, I'll need to merge another feature branch to master to avoid major conflicts. I'll let you know once it's ready. Thanks again!

**Comment by PaulSD** [comment]
For the record:

Python 3 is almost working ... My giant flake8 commit series back in November fixed most of the Python 3 issues without affecting Python 2 compatibility, and I have patches to fix the remaining issues I know about (I was planning to submit PRs for those shortly after the flake8 PRs, but got busy with life and other projects which consumed all of my free time over the winter).  I'll dust those off and submit them after Jenny merges her current feature branch into master.

However, even after Python 3 is working, I'd still suggest sticking with Django 1.11 rather than moving to 2.0, simply because 1.11 is an LTS release which will not force us to upgrade again for a while ... Unless maybe we can support both 1.11 and 2.0 going forward.

@eschipul @jennyq : How quickly do you plan to switch master over from 1.8 to 1.11?  Is it worth trying to make the code work with both 1.8 and 1.11 to make the transition smoother and avoid bifurcating the codebase for a long time during the transition?

**Comment by jennyq** [comment]
@PaulSD, thank you for helping on porting to Python 3! Much appreciated. 
Once the development of 1.11 (T8) is started, there will be no major update for the 1.8 (T7). We'll switch master as long as T8 is ready to deploy. At that point, T7 will stop receiving new features and update unless for the security fixes.

**Comment by PaulSD** [comment]
While we're working on large changes for T8 ...

@aprildh31 wrote a Bootstrap 3 theme for our site a while back, but many things in Tendenci didn't play nice with Bootstrap 3 ... It looked like upgrading Tendenci to play nice with Bootstrap 3 would likely involve either breaking existing themes or forking Tendenci, neither of which seemed like a good option at the time.  So, she managed to cobble together enough of both Bootstrap 2 and Bootstrap 3 to make it work, although it was a pretty big mess.  She is now working on migrating our theme to Bootstrap 4, and the situation there is even worse.

Given that the necessary changes will likely break existing themes, would T8 be a good time to migrate Tendenci to Bootstrap 4?

**Comment by PaulSD** [comment]
While we're working on large changes for T8 ...

@aprildh31 is working on migrating our site to Bootstrap 4, but there seem to be lots of breaking changes, especially in the menus.

Would T8 be a good time to migrate Tendenci to Bootstrap 4 in addition to Python 3 and Django 1.11?

**Comment by PaulSD** [comment]
Fixed in #659

**Comment by eschipul** [comment]
Not to re-open this issue, but I do believe we should be working on 1.11 and calling it t.11.  I say this because I like pinning a project to the core unless it's particularly slow moving (I'm looking at your Debian). Thus leaving this closed but please DO feel free to re-add it to t-11 project.

@jennyq - not sure of the ramifications of moving the branch from 1.8 to 1.11 from a github perspective. But it seems the logical next step given 18.04 LTS and 1.11 LTS are coming out. Must learn to love Python 3 regardless I suppose.

**Comment by PaulSD** [comment]
T8 has already been upgraded to Django 1.11.  See #659.  :)

I guess we can rename T8 to T11 if you want?

**Comment by eschipul** [comment]
@PaulSD  - yes, I'd like to rename it to T11. 

My logic is when we first went open source numerous AMIs were pushed out on T5. At this point converting T5 up to T7 then T5 to T11 is so problematic that you may as well do imports. 

Yes, I would like to rename the branch to T11. I don't want to disrupt the workflow. Honestly I'm living in Kibana and OSSEC as our networks are being pounded with attacks. 

From a vision perspective, I'd like to have Tendenci follow the MayanEDMS or ZUPIPS model where you can either deploy ONLY on https or using dockers and a reverse proxy. All of our internal sites run on dockers, but there are a lot of politics and "theories" on microservices that we just don't have time for.

I'm not sure this issue is the right thread to have this discussion, but I do want to learn more from you, and to share what we have learned. For example we are eliminating chargify and switching to Stripe-Connect. This is a CORE update. That means you can do the same. It facilitates your own business model.

I'm also pushing forward with HyperLedger (Ethereum is great, but there are issues there). With smart contracts, it becomes the ultimate affiliate program effectively where every transaction ad infinitum would continue to pay an annuity to the developer regardless of the hosting provider (for us that's AWS, but no reason it can't be an ISP in Perth or wherever.)

/endOffTopicConvo/

**Comment by goetzk** [comment]
> I'm not sure this issue is the right thread to have this discussion, [...]

You've raised lots of points in the last few posts; would be good if there was another place to discuss them.
kk

**Comment by goetzk** [comment]
Good idea! I have joined.

On 24 May 2018 2:14:22 am AEST, Adam Bark <notifications@github.com> wrote:
>> > I'm not sure this issue is the right thread to have this
>discussion, [...]
>
>> You've raised lots of points in the last few posts; would be good if
>there was another place to discuss them.
>kk
>
>I made a room on matrix.org if anyone is interested. I will of course
>add project maintainers as admins if you decide to use it.
>#tendenci-dev:matrix.org
>
>(If you're not familiar with matrix head over to https://riot.im to try
>it out)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tendenci/tendenci/issues/613#issuecomment-391406668

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by goetzk** [comment]
@jennyq and @eschipul - FYI Adam, Paul and myself are in #tendenci-dev:matrix.org ; if you're interested in joining in please feel free.

(I have just opened related issue #685)

**Comment by jennyq** [comment]
Just got back from my 8-day vacation. Will check it out.

**Comment by jennyq** [comment]
Dear all, T8 has been renamed to T11. It **is** a pretty big jump with Django 1.11 and Python 3 support. Here is the tendenci11 branch https://github.com/tendenci/tendenci/tree/tendenci11. The tendenci8 branch has been deleted. Thanks!
