### ISSUE TITLE
Error on RelatedObjectLookups.js not a function found on /jobs/add/

### ISSUE THREAD

**Issue by ediaz1** [tendenci/tendenci#623]
Error in RelatedObjectLookups.js on 'django.Query' not a function found on /jobs/add/ pages across many sites on theme2018 and create. I believe it is global issue. Discovered through console.

https://github.com/tendenci/tendenci/blob/master/tendenci/apps/jobs/templates/jobs/add.html#L51

```
django.jQuery(function($){
    $(document).ready(function() {
        $('.related-lookup').click(function(e) {
            e.preventDefault();
            showRelatedObjectLookupPopup(this);
        });
    });
});
```
I see several of these RelatedObjectLookups.js when searching them in github and so far seeing the same error throughout: https://github.com/tendenci/tendenci/search?utf8=%E2%9C%93&q=RelatedObjectLookups.js&type=

**Comment by PaulSD** [comment]
I don't see the above code snippet anywhere in Tendenci, including in the history for add.html and RelatedObjectLookups.js ... where did that come from?

django.jQuery is defined in tendenci/apps/base/static/admin/js/jquery.init.js, but nothing actually references that file ... You could add a script tag for jquery.init.js before each call to django.jQuery to fix this.

However, the point of using django.jQuery is to avoid touching the `$` javascript variable, since that variable might be used by other javascript libraries.  In our case, since we are already using the `$` javascript variable for jquery, this isn't necessary.  Maybe we should just remove all of the references to django.jQuery?  The above code would simply be changed to:
```
    $(document).ready(function() {
        $('.related-lookup').click(function(e) {
            e.preventDefault();
            showRelatedObjectLookupPopup(this);
        });
    });
```

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/7b27f43c11d4398856d2de7eeada878ce15456cf
