### ISSUE TITLE
Mention community support in documentation 

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#685]
Hi,
While discussing #613 I realised the documentation at readthedocs has no pointers to support channels.

Before I submit a PR, would you be interested in a changeset which adds a major heading of 'Support' and sub headings for each of:
- GitHub for development issues
- Community Matrix.org channel tendenci-dev for closer-to-real-time discussion
- Forum for other discussion
- Tendenci paid support for issues which need expert / expedient handling
- LInk to www.tendenci.com/directories/
- Tendenci contact form
- Other contact you would like mentioned.

**Comment by goetzk** [comment]
Visibility of this change is blocked by #683 , but I will try and find time to work on this shortly.

**Comment by eschipul** [comment]
@goetzk @PaulSD -- YES YES YES!!!  This suggestion is AWESOME. Absolutely yes.

Any chance you might want to do a pull request on the docs (both 1.7 and 1.11 - why not?) to be sure it follows community norms? I am definitely in favor of listing people with links. Links to your sites can be very helpful (past life - did seo stuff).

And I apologize that I miss the obvious sometimes. I tend to put my head down on infosec stuff and miss things I shouldn't. i spend more time on our ELK stack, NGINX, dockers and OSSEC than code these days unfortunately. (ask me if you have q's on server stuff please. I got ya covered and will be happy to help.)

I also would like to invite any legit committer in the community to list themselves at www.tendenci.com/directories/ 

I've spoken at OSCON and heard stories of people being heavy handed or unbalanced and I'm a little nervous about that part of it - as in I don't want to screw it up. We are a tiny company and I know the project is far far greater than just us.

We are unfunded which limits what we can do economically. Yet please DO tell us what else we can do to help developers? Like I have no idea how to thank the people on transifex.

We used to do conference calls but sometimes the loudest developer isn't the best one. And younger dev's don't use IRC (probably because it mostly sucks). Yet being overly humble isn't the answer either.  Ideally I'd like to be able to promote the humble but great devs that might not otherwise get heard. 

One thing we do have is a lot of natural SEO that we can and are very willing to leverage to promote the team (and by team, I mean the WHOLE team including YOU.) Tendenci has gotten so much bigger and I admit a lot of these questions didn't even occur to me when the adventure started. Please tell us how to leverage everything we have to help you and your people? My email is eschipul [at] tendenci [dot] com although most of my comm is actually done over Signal.

PS - And I gotta give a HUGE SHOUT OUT to @jennyq - our senior committer. She is both humble and wise. Which for me is the very definition of strength and leadership. 

#peace 

Ed

**Comment by goetzk** [comment]
On 5/6/18 13:48, Ed Schipul wrote:

> I also would like to invite any legit committer in the community to list
> themselves at www.tendenci.com/directories/
> <http://www.tendenci.com/directories/>

I just submitted an entry, though thinking about it I should probably
have tried to sell myself a bit better ;)

[..]
> We are unfunded which limits what we can do economically. Yet please DO
> tell us what else we can do to help developers? Like I have no idea how
> to thank the people on transifex.


> . Please tell us how to leverage everything we have to help you
> and your people? My email is eschipul [at] tendenci [dot] com although
> most of my comm is actually done over Signal.

I'm happy to email, but in the interests of transparency (and community
and all that :)) is there somewhere else we could discuss such things?
Would it be an appropriate use of the bug tracker or should we use a
different channel?

(I do have things I'd like to bring up).

thanks,
kk
