### ISSUE TITLE
apps.py files in Tendenci apps

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#695]
Hi,
While working on #691  I'm wondering if apps.py is still used in any meaningful sense by Tendenci's codebase.

To choose a random example, helpdesk:

```
$ cat tendenci/apps/helpdesk/apps.py
from django.apps import AppConfig

class HelpdeskConfig(AppConfig):
    name = 'tendenci.apps.helpdesk'
    verbose_name = "Helpdesk"
```

The log suggests the apps.py is from when the app was still stand alone:

```
$ git log tendenci/apps/helpdesk/apps.py
commit e488e7d40c909c2688840544fafaf7ec8c1cb75d
Author: Paul Donohue <git@PaulSD.com>
Date:   Thu Nov 16 23:54:32 2017 -0500

    Fix flake8 warnings about trailing newlines

commit 58d582f71d93d26fffaed30335c7e7dd20733b1b
Author: Jenny Qian <jqian@tendenci.com>
Date:   Fri Dec 18 17:01:07 2015 -0600

    helpdesk integration
```

Is it still considered 'best practice' to add the name and verbose_name in a tendenci app?

thanks,
kk

**Comment by jennyq** [comment]
Yes, that is Django's preferred way to store configuration and provide introspection https://docs.djangoproject.com/en/1.11/ref/applications/#namespace-packages-as-apps

This is also the place where some signals like `post_migrate` can be registered. We might eventually add the subclasses of AppConfig to the INSTALLED_APPS instead of apps names.

**Comment by goetzk** [comment]
Thanks for the feedback, I will mention them as (still) being recommended.
