### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#714]
I've been working on Travis CI files for Tendenci, T7 was merged today (#713) but T11 requires a recent Ubuntu which Travis doesn't support - directly.

https://github.com/travis-ci/travis-ci/issues/5821

It does support newer Ubuntu's via Docker.

I'm aware Tendenci corp uses dockers internally, I'm wondering if there is a simple testing compatible docker file you're willing to share via the git repo.

https://twitter.com/eschipul/status/60372612042136780
https://www.tendenci.com/forums/c/general/server-configuration/dockers/ 

There are lots of third party files at varying levels of up to dateness and quality but not being a Docker person I'm not the best to judge them.

If a docker image is made available from Tendenci that could be used as a base for doing CI, and probably useful for some developers (per #660).

https://docs.travis-ci.com/user/docker/#Building-a-Docker-Image-from-a-Dockerfile

**Comment by eschipul** [comment]
@goetzk (cc @jennyq ) Karl - going big picture on you again so I'll start with the short version again.

Short answer: "YES".  We are completely wiling to share our docker builds. Why haven't we done so yet? Because we were using CGROUPS and "Jailed Name Spaces" way before Docker was ever a brand name. Unfortunately there are now docker images of T5 that are waaaaay out of date.

Further, our initial methodology predicated the ability of dockers to connect via unix sockets as opposed to IP addresses, which led us to jwilders completely awesome NGINX project nginx-proxy which itself runs in a docker container. Wrap all of that up behind an IDS/IPS/WAF with AWS security groups and you are plausibly secure.

This is probably (initially, as I prefer to share, but at least initially) a private convo. We need distinct docker containers with more nuanced security. Like tendenci core being share across all sites in a hosted environment (speed) as read only. Templates pulled down to a client-file-write-able template modifications. Plus themes, uploads, etc. And lastly a dedicated PostGresGIS container. 

And don't even get me started on how badly ****I MESSED UP THE FIXTURES*** for a launched site.

Dockers - distributed - client can download from us or any provider at any time. 
This complicates updates

**Comment by jennyq** [comment]
Hi @goetzk, Thank you for working on adding tests to Travis CI integration! As Ed said, our current Dockerfile is outdated and we're still working on updating it. 

But for the testing purpose, I think the current Travis CI system should also work for T11. Have you tested it yet?

**Comment by goetzk** [comment]
On 4/7/18 21:51, Ed Schipul wrote:
> @goetzk <https://github.com/goetzk> (cc @jennyq
> <https://github.com/jennyq> ) Karl - going big picture on you again so
> I'll start with the short version again.
> 
> Short answer: "YES". We are completely wiling to share our docker
> builds. Why haven't we done so yet? Because we were using CGROUPS and
> "Jailed Name Spaces" way before Docker was ever a brand name.

[trim big picture stuff for reply]

> Dockers - distributed - client can download from us or any provider at
> any time.
> This complicates updates

Thanks for the reply! Sounds like there is no 'intro appliance' or
'simple Tendenci appliance' you could easily share to get things running.

@PaulSD got back to me in tendenci-dev on Matrix.org with some
suggestions on how to use an existing Ubuntu docker for testing. I will
let you know how I get on.
kk

**Comment by AdamBark** [comment]
I'm running tendenci in a docker container. For your testing purposes do you need a full site setup? I can contribute my Dockerfiles etc. if it would be useful.

**Comment by eschipul** [comment]
@goetzk @PaulSD - your statement is correct --> "Sounds like there is no 'intro appliance' or
'simple Tendenci appliance' you could easily share to get things running." 

We use the Phusion basebox. And then strip out stuff like ssh, have it on a VPC behind reverse proxies and a bunch of security tools and an ELK stack. In other words, our situation evolved and is a bit unique. I'd like to standardize and share more but not all programmers are also InfoSec so it's not something to throw out there. (On a back channel I'll go into more detail.)

@AdamBark Yes, sharing your docker make files would be helpful. Ours is very specific to our environment unfortunately.

I'd love to see a good docker-make-file that decouples these three:

1. tendenci core (execute, read, but no write permissions)
2. postgres db (only accessible on internal subnet)
3. conf, manage, theme, media, logging - ideally mapped to file system

(I'm wrong a lot so that might not be the right way to slice it up, I'm open to better ideas?)

In particular having communication via unix sockets. And being on 16.04 or 18.04 (although I don't know if phusion base box or an alternate image is stable yet so 16.04 is still kind of baseline I guess.)

OverlayFS2 via systemd - I can share that config with you if you'd like.

I'm not fully into the full on microservices-extreme-minimalist stuff, but I do believe three-ish containers connected by sockets would be helpful. I know there are a number of docker make files on hub for Tendenci, but none that I would run in a production environment. 

As always, I'm humbled by the open community forming around Tendenci, from the translators to the testers and documentation and of course developers. It is truly very humbling. I like knowing ALL of us, most definitely including the three of y'all are trying to make the world a better place.

@jennyq - you rock. I know I say that a lot. But I figured it doesn't hurt to say it again. You are completely awesome and all of us are very appreciative. #rockon

**Comment by goetzk** [comment]
@AdamBark Have a look at this for where I had got to -its a weird halfway between what I successfully submitted for T7 and the final T11 destination. I can't tell you what needs to change off hand as I haven't looked at it since the last commit.
https://github.com/goetzk/tendenci/blob/t11-travis/.travis.yml
For the purpose of testing it doesn't matter if its nice docker or ugly docker, it just needs to run on Travis and work. 
As a side note, I've done some experiments with Gitlab CI integration instead of Travis as its possible to run up arbitrary VMs for testing in; no real results yet due to time.

@eschipul feel free to contact me privately if it will ever be useful to you :)
kk

**Comment by KrunchMuffin** [comment]
Has anyone been able to get this running in Docker? I haven't tried, but if it can't be done, I won't.

**Comment by eschipul** [comment]
@KrunchMuffin - Yes, our sites all run in dockers at AWS. We are currently *not* using AWS container services because we've been using CGroups and Jailed NameSpaces for years and had it automated prior to that.

Why no makefile? Because it keeps changing and producing a stable makefile is a long time goal but is fraught with challenges relating to the server config more than the app. 

That said - if you write one - that would be awesome because the ones out there written by others on docker hub are way out of date.

If you launch Tendenci in a docker container(s), it should work just fine. Plus I see the phusion basebox has been updated to 18.04 which is what I would recommend if you aren't using the official canonical image. https://github.com/phusion/baseimage-docker#readme

**Comment by jucajuca** [comment]
I did a working dockerfile and docker-compose file for tendenci.

check it out:
https://github.com/jucajuca/docker-tendenci

will deliver you a clean tendenci installation with the default minimal settings. Not using virtual env because err... docker is already on isn't it? ; )

**Comment by jucajuca** [comment]
@KrunchMuffin @goetzk @AdamBark 
I created a working docker and docker-compose file for tendenci 11

check it out here:
https://github.com/jucajuca/tendenci11-dockerized

It will create a default tendenci installation.
The tendenci installation (not the docker one) still demands more configuration. see: https://tendenci.readthedocs.io/en/latest/testing/post-install-checklist.html

**Comment by eschipul** [comment]
@jucajuca - I created a project team for the docker deploy under the tendenci org and invited you to it after forking your repo. (It's important to me that it shows you originated it and did the code.)

@goetzk @AdamBark if y'all want to join as well i can send you an invite?

**Comment by jucajuca** [comment]
@eschipul 
link & close the tread?

**Comment by AdamBark** [comment]
> @jucajuca - I created a project team for the docker deploy under the tendenci org and invited you to it after forking your repo. (It's important to me that it shows you originated it and did the code.)
> 
> @goetzk @AdamBark if y'all want to join as well i can send you an invite?

Can do

**Comment by goetzk** [comment]
On 19/5/19 08:03, Adam Bark wrote:
>     @jucajuca <https://github.com/jucajuca> - I created a project team
>     for the docker deploy under the tendenci org and invited you to it
>     after forking your repo. (It's important to me that it shows you
>     originated it and did the code.)
> 
>     @goetzk <https://github.com/goetzk> @AdamBark
>     <https://github.com/AdamBark> if y'all want to join as well i can
>     send you an invite?
> 
> Can do

I don't know when I'll have time next, but I'm happy to join in and help
when I can again.

Karl.

**Comment by maxdatamax** [comment]
Can you please add me as well?
Thank you.
Max

**Comment by goetzk** [comment]
Looks like Tendenci and Docker is now a solved problem - I'm marking this as closed.

(I will try and use it another time, just not yet!)
