### ISSUE TITLE
Tendenci11: Drop Python 2.7 Support

### ISSUE THREAD

**Issue by jennyq** [tendenci/tendenci#715]
The EOL of Python 2.7 will be on January 1st, 2020. That's about 1 year and 5 months away from now. Since Python 2.7 is not fully tested in Tendenci11, I think we should just remove the Python2.7 compatible code from T11. Thoughts?

**Comment by surajprasad** [comment]
I think it is a great step. Python 3 will give a boost to the overall performance. Removing the python 2.7 will also help since I faced a bit of a trouble because some of the django components had to be installed with older versions. 
When is the expected official announcement for the tendenci11? I see the upgrade instructions have been put up in readthedocs. Is there also a doc with the changelog? I would love to know of new features/apps etc.
Most importantly, if there are plans to have a shop/cart app in the package. 
Tx.

**Comment by jennyq** [comment]
@surajprasad thanks! Once it is thoroughly tested, we'll make the official announcement. I don't have the specific date, possibly next week I think. 

The changelog can be found here:
https://github.com/tendenci/tendenci/blob/master/CHANGELOG.md

Regarding the new features, there are something to be added to T11. But currently I don't have the list.

**Comment by jennyq** [comment]
Resolved in T12.
