### ISSUE TITLE
Sponsorships App

### ISSUE THREAD

**Issue by ccwallace** [tendenci/tendenci#729]
I work with a non-profit that needs to manage child sponsorship records where one donor could sponsor many children on monthly recurring donations. I'm relatively new to the Tendenci project, but it appears to have all the other features we would need, so I'm wondering if there are any plans to include a sponsorship module in the future. If not, would there be anyway to mimic this feature in the current Tendenci release? Thanks!

**Comment by jennyq** [comment]
Hi @ccwallace, I think there are two possible ways you can mimic the feature. 

1) The custom forms with the recurring payments. 
https://www.tendenci.com/help-files/how-enable-recurring-payment-custom-form/

2) Memberships with auto renew. 
https://www.tendenci.com/help-files/how-enable-memberships-auto-renew-stripe/

**Comment by ccwallace** [comment]
Thanks for the reply and info! Just curious, would a sponsorship module be welcomed if it were to be developed?

**Comment by jennyq** [comment]
I think it'd be a great addition to Tendenci. @eschipul, if it were to be developed, can it be included in core?

**Comment by eschipul** [comment]
@ccwallace @jennyq In principle I like the idea of a sponsorship module. Yet we've done a few similar projects like this in the past so I know there are some challenges. All of them having to do with three areas:

1. Privacy
2. Relational Database Records
3. Breaking the "a user is a user is a user" rule where everything is an attribute of one user object stored in one location (user object attached to profile object)

In greater detail - 
1. Privacy - if these are kids there are numerous laws and restrictions on who can see them or view their information. And these laws are in place for a reason - to protect our children. Hence the UI is much more complicated. Not that it can't be done, but it is somewhat precarious if one person misses checking a "private" option on a user profile.
2. Relational Database Records - Tendenci is designed for accountability and that includes tracking of money. The invoice object is tied to any type of payment and accounting entries under the hood (although it is not an accounting system, we need these to facilitate api integration and exports.) If a user is deleted it orphans all of these records. This could be fixed with outer-join queries on the user object but that again is counter to the base design of the software.
3. A user is a user is a user - Tendenci is designed specifically to have one (1) user table and everything else is an attribute of that user. They are attached to a profile. They add content which they then have permission to edit if approved by a super user. Again my concern is that if a superuser picked a bad password (and they do - reference JohnnyCrack5 and Metasploit utilities) then kids records could be exposed. This isn't a software issue, it is a human issue. However it would still come back to the project.

Flipping over, there is one area of tendenci that does BREAK the "a user is a user is a user" rule and that is event registration. This was done to allow for Table or Team registration for example. if a company buys a table for 10 they may not have the names of the guests so it "tries" to match the registrant up to an existing user record by email, unless they are a super-user, so this is the one exception.

I kind of think about this like I think about MOOCs - where SSO might be a better option because you may not want a super_user on the site (summer intern adding content) to be a super_user on your instance of EdX MOOC given in that context they are a student and shouldn't have access to everything the instructors can see.

As always I'm open to a pull request, I'm just saying this would be swimming upstream against some of the core design principles of the software. Thoughts?

**Comment by eschipul** [comment]
Moving over to "wish list" and closing the issue for now.
