### ISSUE TITLE
user profile image issue #499

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#731]
I am getting a LOT of complains about the profile images, people don't understand why and how the have to go gravatar.com create an account link it to the website. It is too much hassle for them, specially I am dealing with older people, not very tech savvy, I think this should be optional if we want to enable people to upload their profile images.

**Comment by eschipul** [comment]
I also don't like the reflex. But it was me that REMOVED the ability to upload a profile image. Why?

Because hackers were using client sites to upload profile images that were effectively command and control servers for malware or, if another exploit of tinymce were found, they can upload three images and using the geolocation xif data in the image that is more than enough to create a binary if the permissions on the server aren't correct.

Example: https://blog.trendmicro.com/trendlabs-security-intelligence/picture-perfect-crylocker-ransomware-sends-user-information-as-png-files/

Steganography: https://blog.sucuri.net/2013/07/malware-hidden-inside-jpg-exif-headers.html

And here is a tutorial on how to hack a server, in this case with php. While our servers don't process php, I can't control what happens in the wild on self hosted servers that might be using cpanel or similar to maintain the environment. Therefore image uploads are severely restricted to handle xif injections.

Now, all of that went down with PIL, not PILLOW, but I see no end in sight to the fundamental security flaw. When we remove ALL XIF data, which I wanted to do (and may actually be the case in the photos module) photographers got upset because people were stealing their images saying they didn't have a copyright.

That frames the problem. Suggestions?
