### ISSUE TITLE
restructure project memberships

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#748]
I defined a few membership types, and established some related groups independently. 
But, I now realize that Tendenci generates a membership group independently, based on the membership name. For example, I had defined membership type 'student', and Tendenci seems to have automatically generated group 'Membership: student'. 
The upshot of this, is that  i have a messy relationship between membership types and the group names I wish to use.  So, I deleted all existing members, and hoping to begin again with a more rational membership name set.

I then  deleted the membership type 'student'.  Now I would like to regenerate that membership type ('student'). However I get a duplicate key error:
IntegrityError at /admin/memberships/membershiptype/add/
duplicate key value violates unique constraint "memberships_membershiptype_name_key"
DETAIL:  Key (name)=(Student) already exists.

Is there any way out of this bind??

**Comment by replaceafill** [comment]
@rjdini I think your problem is that you still have the "soft deleted" objects in your database. Even if you don't see the content either in Tendenci's UI or the Django admin, Tendenci [doesn't delete](https://github.com/tendenci/tendenci/blob/5ba6cb05c448dfc9bc575f24588f773280bf2faa/tendenci/apps/perms/models.py#L124-L126) some objects permanently. It just hides them. You need to run the [delete_soft_deleted_items](https://github.com/tendenci/tendenci/blob/master/tendenci/apps/base/management/commands/delete_soft_deleted_items.py) command in your server to remove them permanently.

**Comment by rjdini** [comment]
Thanks you very much!
That does the job.
I'm closing this issue.

**Comment by eschipul** [comment]
@replaceafill @rjdini - on a related note, I do use /explorer/ (from e-pantry) extensively. For some reason clients frequently delete their /navs/ so they also gets soft deleted (e.g. status=False). There are some examples posted at:

https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/

I need to get those added to fixtures. On my list...

Also don't forget you can play using https://demo.tendenci.com (login as admin/admin). The only downside to testing on the demo site is there isn't much data and it does reset every two hours because of spammers.

#peace
