### ISSUE TITLE
Event registration security error

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#752]
My use case is: two registration prices; public pay, members are free. Single custom registration form, which can be viewed by public.

Now, when public person calls registration form, and selects  to register, two option pannels are shown: one for members, another for public. Person selects member registration, and a form opens that has member price selected. However the applicant must supply email and user number. It turns out that if the applicant enters any email of _any_ member; then the registration will be accepted, provided that the Member ID is given. BUT it turns out that one can insert _any_ Member number and any names, and tendenci will accept the free registration!   I think should Tendenci should at least check name and member number  against the email.

**Comment by jennyq** [comment]
Hi @rjdini , does your pricing have any restriction? If a pricing is only meant for members, check "All members can use this pricing" checkbox, and uncheck "Public can use this pricing" and "Signed in user can use this pricing" checkboxes. Please also check if the setting "Anonymous Event Registration" is set to "validated" or "strict":
https://yoursitedomain/settings/module/events/#id_anonymousregistration

**Comment by rjdini** [comment]
My orignal observation is rather generally true, @jenny

I tried checking the 'all members' and 'sign-in...', with validated, and
with strict.

In all of these cases, if I chose the member pricing, I can fool the
registration.

I sign in as member A. Then in the registration form I chang member A's
email to member B, and put any old number into the member number field,

and tendenci is will to register me for the event.


I also notice that I cannot unslect 'single custom form' filed. I though
maybe I could solve this problem using two custom forms - but

I cant generate two custom forms (because the button is stuck on
single). Maybe this points to some broader pathology on my end??

thanks so much for you continual assistance!

regards rjdini

**Comment by rjdini** [comment]
I have to say @jennyq, there is definitely a problem here, that goes beyond honor registration (which is OK).
I have demonstrated that the following:
I login as valid member A. Then register with the name of A, but the email of valid member B. Tendenci accepts this registration.
Now, I login as B, and check events. I find that I am already registered for the event (because A did that with my email). But when I check the roster of registrants I see that the name of A is on the roster, and not me (B).
Surely if the email of B is the criterion for registration, then it should be B's name that appears on the roster?

**Comment by eschipul** [comment]
@rjdini - event registration is one of the few areas that does not create a user record if one is not found. The reason is because of “table registration” or “team registration” ( golf foursomes or tennis partners).

In those scenarios the webmaster or executive director might register a 10 person table where everyone has the same email address until the individuals attending are identified by name. And even then they may leave one email address for the individuals (human issue, not software.)

MemberIDs, unfortunately in practice, some NGOs or associations have legacy policies that use member ids that might be personally identifiable information such as a social security number or a combination (again, a human issue.)

Thus, when using the honor code to register, the price is determined by the status the individual provides and the system makes a “good faith” effort to identify them by the only unique identifier which is email. 

You can make first and last / surname required on your form to solve the roster display issue. 

What I see in practice is very rarely does someone “cheat” and if they do, they are kicked out of the association on ethical grounds. 

I do see your point on A and B, but between turning off honor system reg, or requiring more detail on reg form, the system is working as designed. It’s up to you how you want to configure it. 

Or am I missing something?

**Comment by eschipul** [comment]
Closing. Tagged "best practices" as this would make a good help file at some future point.
