### ISSUE TITLE
form email field creates a user

### ISSUE THREAD

**Issue by jucajuca** [tendenci/tendenci#777]
Hi,
I noticed that if the contact form has an e-mail field, this data will be saved and a user is automatically created. 

This is a problem because it is not compliant with the new EU General Data Protection Regulation (GDPR). Is there any way to have an email field and avoid the creation of an user?

**Comment by eschipul** [comment]
@jucajuca given the prevalence of spam I am questioning my original design to try to record the lifecycle of a member from early email sign up to event attendance and hopefully being converted to a paying member of an association. However, that is the current data structure because I have a strict policy of "a user is a user" and everything else is an attribute of that user record.

Example for "a user is a user" would be a Graduate Student might teach class at a University and is therefore both an "employee" and a "student". I don't believe in having two user records for one person or in having a table for each type of person. This causes data redundancy and makes it impossible to see your data accurately.

YOUR ARE CORRECT However - I *do* think it is time to have a checkbox on forms that gives options such as:
1) Create a user with this form?
2) Do not create a user with this form, but IF a user exists make a note that they contacted and associate the form with that user.
3) Do not attach this contact form to any user or create a new user.

That seems like a reasonable mod. Suggestions on that thought?

Second question: COMPLIANCE NOW is in place although not as convenient as we'd like to see.

Options:

1) To NOT create a user and have a contact form you can simply not map the fields in a custom form or even use the theme editor to embed an email subscription list provider. You can do this now, although not ideal and I understand that. We'd welcome a pull request to make this easier.

2) Use data explorer /explorer/ to find any data that doesn't follow all of requirements of GDPR and then simply delete it. Not very efficient but it does work. (note you can't delete through explorer but you can link to the related "delete" page to achieve the same result. Some example SQL here:
https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/

3) I personally go to /admin/auth/user/ - sort by ID descending and delete them in bulk. I also search for strings from TLDs with bad reps like xyz. Bulk delete.

4) LASTLY but IMPORTANTLY - there is also the issue of previous employees or editors on the site which might delete relational data. For that I use "merge users". Of course first you need to either make their names the same by editing each record with "content" and "editor" for first/surname or give them the same email address. Either will work. Then merge the records.
This help file is a bit out of date but explains the process overall:
https://www.tendenci.com/help-files/merge-users/

Our general guidance on GDPR is here, https://www.tendenci.com/help-files/gdpr/  - although pretty much it says Tendenci is open and GDPR compliant depending on if you are following the law, which we believe everyone should. Europe is definitely leading us all on the importance of limitations in the online world IMHO.

Thoughts? Pull requests? Because you are correct, GDPR compliance IS important, it is reasonable, and we thank you for the help!

**Comment by jucajuca** [comment]
I see that the rationale here is the problem.

Someone that wants to send us an email is _not_ an user or a member. Is just some random person that wants to contact the organization. No we do not have the need nor the rights to track those persons.

Regarding the technical part: there is already a field "text" that will not save the email. But it also does not sanitize the data. Basically is quite simple, it is just about deactivating the function that forces an email field to be saved into the db.

This does not have to be so convoluted. Seriously. Just a mundane contact form will do. People come, fill in the fields, we get an email. Everyone is happy and the DB is clean. : )

**Comment by eschipul** [comment]
I agree @jucajuca . At least in principle. 

The devil is in the details. Sanitizing the data by datatype and object is critical. Clients love to read a marketing article about playing back data to the user for "content marketing" or "marketing automation" not realizing spammers will make their last name www . bad-guy-url . com and people will click it.

This end user generated content, depending on where the email is generated from on the site is typically saved in at least two places.

1) The custom form entries are saved. This is critical because spammers get domains banned on purpose to block competitors and the only fall back is to retrieve the data directly from the db. Export form data. (you can of course manually delete it).

2) If fields are mapped to a user object those are stored. Otherwise you can't do basic stuff like accept a credit card donation.

In a perfect world, we could leverage the custom form mappings, create the user object, save it, process the transaction, then maybe a server log showing the "token" (it NEVER stores credit card numbers, just the token associated with the transaction.)

Are we over-thinking this? Ianal but it seems like a cron job to clear out all of the data every 60 days would allow accountants to reconcile, and let everyone remain in compliance? Cause like I said, the EU seems to be leading all of us on rational data use and retention. We're OPEN so ya, we love it, but I can see other vendors complying differently.

What is the quickest path to production and compliance knowing all of the variables?

**Comment by eschipul** [comment]
** note - you could also do client side validation using jscript for the email and assign a class to the field on the form. Then attach the form to an alternate template. That would definitely be something I'd like to see pulled into core templates.

**Comment by jucajuca** [comment]
Again the whole rationale is convoluted. No offense. 

A contact form should do just the following: let the user fill in the fields, including email. Then send that message to the email address that we specify. for example hello@ourganization.com.  There is no need to create users, track people, manipulate data or anything else.

Best example: contactform7.com. It has captcha, I've been using for years and never got spam emails.

- For spammers: there is captcha, which is already out of the box in tendenci.
- If you want to save the email, there is also a function in tendenci that allows to automatically add the address to a group. "Special Functionality, select "Subscribe to Group (Automatic)"

- Best and quickest solution to compliance: deactivate the automatic record of email addresses entered through the email field.

hope this helps to make tendenci simpler and also GDPR compliant.

**Comment by eschipul** [comment]
(1 of ?) @jucajuca - YOU ARE CORRECT after I have given much thought on this subject. 

I like to think things through fully. I apologize for the delay responding. Maybe I take all of this too seriously, but there are many organizations globally using Tendenci for various purposes and it is crucially important to me at an ethical level to "do the right thing". You gave me a lot to think about.

Further I *DO* agree with your proposed solution. It is time for contact forms to no longer create a user and profile objects. My original architectural db design didn't anticipate the prolification of spammers and hackers using social influence.

There are subtleties that I would like to articulate further, that is for another time. 

I'd like to address this in several parts because it is kind of a big deal: 
(cc @jennyq )

**Comment by eschipul** [comment]
(2 of ?) @jucajuca @jennyq 

1) GDPR - Tendenci is the ONLY AMS that is GDPR compliant fully as far as I know. Hear me out.

By that I mean, Tendenci provides all of the tools for anyone to maintain a GDPR compliant site, and that is 100% on the organization to use those tools, In an effort to not duplicate information this help file is admittedly minimalistic as laws change and that is up to the organization. 
https://www.tendenci.com/gdpr/  At a minimum you can always go to example.org/explorer/ and select from there even if at a database level. Then connect and update the database directly (explorer doesn't allow update or delete statements in the SQL for obvious reasons.) 

It is ultimately the client's responsibility to manage their data. Period. But we had all of the tools in place *prior* to the passing of the GDPR. 

So if asked "Is a Tendenci site GDPR compliant?" the response is "Yes, just as much as a car is as safe as the driver." All of the tools are there. But yes, they must be used. Could it be easier or automated better? Probably and we'd welcome a pull request.

(Side note: Europe is leading the way on online privacy and Silicon Valley should pay more attention and take it more seriously. I love the fact that you care. I do.)

**Comment by eschipul** [comment]
(3 of ?) I *do* agree with the larger issue that the architectural design is no longer applicable to current reality given the prevalence of spammers. This is a bummer, but we can't deny reality.

**Comment by eschipul** [comment]
@jennyq  - Please *remove* the default functionality to create a user object from a contact form. Check for an existing email address match and mark an eventlog, but don't update the user or profile object, only user activity with a link to the admin-back-end view of the contact form. (e.g. similar to events registration which tries to correlate, but not create users.)

Global explanation: Currently contact forms create a user object and therefore a profile object. My original intent was to observe the evolution of a person as they contacted, then became a member, if they renewed or not, etc. Unfortunately times have changed and clients (hosted and self hosted open source) are being inundated with spam contact forms even if they configure recaptcha.

Last thought - I am *not* 100% on the method of implementation. I am open to alternative methods of implementation. Some options include, but you may have a better idea:
1) site settings on default?
2) form specific, "create_auth_user_on_submit" or siilar, boolean?
3) just remove the functionality by commenting it out so someone can fork and add it back if that is their thing?

I initially suggest option 3, but I'm open to other middle-ground options.

**Comment by jennyq** [comment]
How about option 3 with the conditions? We can disable the user creation on form submissions except for these two occasions:   1) when forms have the "Subscribe to Group" functionality selected, 2) when form submissions need to set a recurring payment or payment. What do you think?

**Comment by eschipul** [comment]
I agree @jennyq - I had forgotten about the variations of newsletter sign up and payments. But your suggestion would eliminate the vast majority of spam contacts.

I’d add to that I don’t think any email or email domain should not be able to register or contact with that email. So if emailblocks blocks has example.com, anyone with an email in that domain (like “joe@example.com”) would not be able to register or submit a form or register for an event.

**Comment by jennyq** [comment]
Added a setting "Create User on Form Submissions" (default to false) to give the site owner more flexibility.  https://github.com/tendenci/tendenci/commit/f698646450bbda7e0fc66d337bdc8110d3d73910

Note that - Even if this setting is set to false, a new user will still be created if payment is involved or "Subscribe to Group" functionality is selected. To make your site GDPR compliant, you can add a new checkbox field to your form to obtain user consent.

**Comment by lashirley21** [comment]
Hello there jucajuca , 

A help-file has been created and you may use for guidance. 
https://www.tendenci.com/help-files/contact-form-submissions-create-user-profile/

Cheers!

**Comment by surajprasad** [comment]
Hello @jennyq @lashirley21 
I wanted to implement this for my site currently running version 11.0 but I could not find the option to turn it off as per the document linked above, I thought I needed to upgrade the site and followed the instructions for a minor upgrade as per the docs. However, I still cannot see the option to turn off user creation with contact form submissions. 

I am also experiencing a lot of spam submissions via the contact form even though the captcha is turned on and I tested it by submitting a new entry. I am not sure if the captcha is being gamed or if spammers are actually taking time to manually spam, either ways it is making things weird. Is there anything I am missing in the implementation?

Could you also tell me how I can delete all entries in the contact form safely? There is no option to delete entries only to export them.

Thanks.

**Comment by jennyq** [comment]
Hi @surajprasad,

What version of Tendenci your site is running now? Please upgrade your site to the latest version of Tendenci. https://tendenci.readthedocs.io/en/latest/upgrade/upgrade-to-tendenci12.html

To delete form entries, you can go to admin backend at https://www.example.com/admin/forms/formentry/. Check entries to be deleted, then select "Delete selected Form entries" in the Action dropdown, hit the "Go" button.
