### ISSUE TITLE
Button to theme clear cache in admin 

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#808]
Hi,
Although #525 is resolved it doesn't provide a mechanism to directly clear the site cache without navigating away from the theme.

From what I understand the following techniques can be used to view the site without caching (to check for theme changes in progress):
- add ?theme=NameOfTheme as a get request to the site URL

And the following can be used to clear site cache:
- Change themes (select NewTheme in the sidebar then swap back to MainTheme)
- ssh to server and `python manage.py clear_theme_cache`
- ssh to server and `service tendenci restart`

I hope an admin only 'clear site cache' button won't be too hard to add given the other infrastrucutre is all in place.

**Comment by jennyq** [comment]
Tendenci sites usually run as the user `www-data`, and `www-data` user does NOT have the permission to run the command `service tendenci restart`. Hence, such button would not work. 

I'd recommend to disable the template caching when you want to make any change to your site...

**Comment by goetzk** [comment]
I agree it couldn't - at least not without a wrapper and sudo configuration - but tendenci could invoke clear_theme_cache.

I will check later, but I don't recall template caching being something which can be disabled from within the admin UI ; preventing admins without system access from readily making theme changes.

**Comment by jennyq** [comment]
Changing theme would automatically clear cache. But template caching is a different concept. Enabling the template caching is basically enable the template cached loader for the performance reason [https://docs.djangoproject.com/en/1.11/ref/templates/api/#django.template.loaders.cached.Loader](https://docs.djangoproject.com/en/1.11/ref/templates/api/#django.template.loaders.cached.Loader). You'll definitely need to disable it when editing in theme editor. 

To disable template caching, just make the function call `disable_template_cache()`. That is,  in your `conf/settings.py` [https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L27](https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L27), 
change from 

     if DEBUG:
          disable_template_cache()

to 

    #if DEBUG:
    disable_template_cache()
   
Then, a site reload is needed. That's why it cannot be added as button for admins as well.

**Comment by goetzk** [comment]
Hi Jenny,
Thanks for explaining the current workings - I've closed the issue for now.
