### ISSUE TITLE
The payments module doesn't require a login to view payments

### ISSUE THREAD

**Issue by AdamBark** [tendenci/tendenci#827]
I assume they're pretty hard to guess but I just noticed that anyone can see details of a payment. Also the link to the payment status is viewable and the invoice link works too. They all seem to use some sort of hash for the URI so they should be difficult to guess but if you have it you can access quite a bit of information.

Seeing as these links are emailed to admins they could be seen by email server admins too.

**Comment by AdamBark** [comment]
I made a pull request #828 for the payment module. I'm happy to do the other modules too if you want them.

**Comment by eschipul** [comment]
@AdamBark you make an excellent point. It, being able to see a hashed URL for payment confirmation is in fact there for a reason. From experience, requiring login for all event registrations significantly reduces online registration. Executive Directors of associations then get bombarded with phone calls for registration, faxes (I know? Who knew people still had fax machines?).

If you look at Meetup or Eventbrite or similar, they have the weight to require people to login. However, my challenge is one of the goals of Tendenci is privacy and security. Therefore there are no back-doors, secret logins, or central aggregation in a central login database. 
For example, Tendenci is a far better tool for protesters in Hong Kong or North Korea to use to organize themselves to organize. The rest of us would never know they were using Tendenci. We are the anti-Facebook for groups.

(OK, off-topic. Sort of. But insert Ed-tirade-here warning against the use of central CDNs for fonts, css, etc, in the themes. They make my head explode as a singular point of failure. I really don't like them. urls.py is cool, but it also makes theming a challenge. We are missing a main.py file to autoupdate via distributed servers via VPNs or similar to preserve privacy. This is also a huge problem trying to monetize this project because there is no single source to know the number of sites that use it. Yet that is by design for privacy and security and to limit monitoring. But I digress....)

So YES, I strongly agree with your point on security, which is after all one of the primary goals of Tendenci. A pull request is far more secure than random php plugins for example, and I know you get that and are as security focused as the rest of us (which is awesome!)

I need to think on this one. Like events needs an obfuscated URL for anonymouse, but maybe not resumes or jobs or memberships. It would need to be module specific. I need to think on this one. YES, the pull request is awesome but it needs to be module specific and I'm not sure which yet. 

Your advice is appreciated given the nuances?

**Comment by JustinLewisSMA** [comment]
My 2 cents: I think the url should be login with an option to make it public (while still having the hash in the URL). Then anyone with the should be able to pay the invoice. From a usability point of view, that's INCREDIBLY helpful as it's often an admin assistant or some such that needs to pay, but doesn't have the bosses login information.

A lot of other AMS software provides this (not saying it's smart) and it's been really useful for our staff.

**Comment by jennyq** [comment]
It seems that the link to view payment is being sent to admin only, so it's okay to make it login required. Thanks @AdamBark !

@JustinLewisSMA, I agree with you and Ed. The invoices remain the same.

**Comment by eschipul** [comment]
Thank you @jennyq @AdamBark @JustinLewisSMA on sharing ALL of our values on the importance of security. 

I'd have to test it, but my intention with the original code was for the super_user/admin to allow anonymous registration and allow payment and receipt with an obfuscated URL.

In other words, I'm not sure we're talking about the same thing. And I *respect and want to understand the specifics*? Hence:

@AdamBark - can you link an exact example from a site (please don't use demo . tendenci . com as that container resets every two hours to deter spammers)? 

I ask this because "payments" technically means /py/ but I'm not sure that's what you mean. Are you actually talking about just payments, or invoices view, or payments for a specific module?

I don't want to hastily close this issue if we don't, and I do not yet, fully have an understanding of the issue.

@JustinLewisSMA - yes I realize I over-analyze, but I don't understand exactly exactly what you mean when you say 

> "A lot of other AMS software provides this (not saying it's smart) and it's been really useful for our staff." 

- again, specific examples are needed. Perhaps a printed PDF in icognito mode from the brave browser while anonymous? And it doesn't have to be sent via github, but emailed to helpdesk @ tendenci . com would work. Or post on github (which I prefer of course) but use sketch to blur our any sensitive or personally identifying data.

It is important for all of us to remember it's not just tendenci, but also nginx and ubuntu or debian that have to be configured correctly to keep them secure. This project is, by definition, playing with live ammo given the importance of associations' role in society, so we must be security focused first and that is a mindset more than a checklist. 

 Hence my serious dislike of CDNs and my constant worry over iframe included content. A third party can always change that js file later as FB did with their "like button" (another issue to address.)

We are the OPEN anti-facebook for associations where there is no one person with access to everything. I beg of you all to think like a human rights activist in a hostile geopolitical climate. We aren't here to judge, so I personally seek to LIMIT aggregation. 

Clients frequently ask to increase upload size (cough @JustinLewisSMA cough) without realizing the damage that could possibly occur from a well intentioned request. It isn't intended to be dropbox. Or a pull request to make s3 integration easier via site settings is a way to handle this.

For example, this hack is NOT a Tendenci issue, it is an NGINX issue on debian variants, but it still has the potential to have a negative impact globally. https://legalhackers.com/videos/Nginx-Exploit-Deb-Root-PrivEsc-CVE-2016-1247.html

Action items - LINKS and EXAMPLES please. I take it seriously, but we aren't mind-readers so we need specifics please?

**Comment by jennyq** [comment]
Hi @eschipul, 

My understanding is that this issue refers to the payments view (with transaction details). It is also what @AdamBark addressed in the [PR](https://github.com/tendenci/tendenci/pull/828). It does not affect invoices and make payments. @AdamBark please correct me if this is not the case. 

The example url would be (replace {id} with your payment id and {guid} with you payment guid):
https://www.example.com/payments/{id}/{guid}.

**Comment by AdamBark** [comment]
You're right @jennyq. I did mention some other modules that are accessible in the same way but those links are never emailed; they are, however, linked to from the payment but that loophole should now be closed.

**Comment by jennyq** [comment]
Closing it as the issue has been resolved.
