### ISSUE TITLE
Tendenci PayPal support

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#842]
Hi Jenny, Ed, and co.

I'm wondering what the current state of PayPal support is for new deployments.

I have a customer who insists on paypal (for reasons) but I can't seem to able to find a version which is currently supported by both Tendenci and Paypal.

Tendenci documentation mentions "PayPal Payment Standard" and "PayPal PayFlow Link".
https://www.tendenci.com/help-files/setting-up-online-payment-processor-and-merchant-provider-on-a-tendenci-site/

PayFlow link has been absorbed in to a thing called 'gateway' which mentions "Pro" (API driven) and "Link" (The one we both know). Unfortunately the developer page says Link is Legacy and "... available for pre-existing users." so it seems I can't use it for a new deployment.

https://www.paypal.com/au/webapps/mpp/payflow-payment-gateway
https://developer.paypal.com/docs/payflow/payflow-gateway/#related-products

I can't be positive but I think Tendenci's other supported option is Website Payments standard, in the developer documentation as PayPal Payments Standard (I think....?).

https://www.paypal.com/au/webapps/mpp/website-payments-standard
https://developer.paypal.com/docs/integration/web/?mark=PayPal%20Payments%20Standard

This last bit is the part I'm least sure of, so if its actually a different paypal component which Tendenci is integrating with that might be my lifeline in this situation.

I did look in to doing Tendenci support for PayPal Express Checkout (to try and free us of paypals constant churn in APIs) but it hasn't been funded at this time.

thanks,
Karl.

**Comment by PaulSD** [comment]
The "PayPal Payment Standard" instructions on https://www.tendenci.com/help-files/setting-up-online-payment-processor-and-merchant-provider-on-a-tendenci-site/ are still supported by PayPal as "Website Payments Standard" or "PayPal Payments Standard".  However, PayPal keeps moving the settings around, and the Tendenci instructions are missing a few important bits.
Current PayPal setup instructions:
* Log in to PayPal
* If you have a "Premier" PayPal account, click the gear icon, then "SELLER TOOLS"
* If you have a "Business" PayPal account, click the gear icon, then "Account Settings", then "Website Payments"
* Click "Update" next to "Instant payment notifications"
** Click "Choose IPN Settings" or "Edit settings"
** Set "Notification URL" to https://www.example.com/payments/paypal/ipn/
** Select "Receive IPN messages (Enabled)"
** Click "Save"
* Go back to "SELLER TOOLS" or "Website Payments", then click "Update" next to "Website preferences"
** Set "Auto Return" to "On"
** Set "Return URL" to https://www.example.com/payments/paypal/thankyou/
** Set "Payment Data Transfer" to "On"
** Copy the "Identity Token" listed under "Payment Data Transfer" to the "MERCHANT_TXN_KEY" setting in conf/settings.py in Tendenci
** Set "Block Non-encrypted Website Payment" to "Off" ("On" doesn't work with Tendenci)
** Set "PayPal Account Optional" to "On" (Optional, but you probably want this so that your users aren't forced to create/use a PayPal account)
** Click "Save"
Tendenci configuration:
** In conf/settings.py set "PAYPAL_MERCHANT_LOGIN" to the email address you use to log in to PayPal
** In conf/settings.py set "PAYPAL_POST_URL" to 'https://www.paypal.com/cgi-bin/webscr'
** Log in to your Tendenci website as Admin, go to "Site Settings", and set "Merchant Account" to "paypal"

"PayPal PayFlow Link" was the name of a PayPal service/product, which had a monthly fee and provided additional functionality (eg custom reporting) beyond what you get with a normal PayPal Business account.  For marketing purposes, the product was "replaced" with a new product named "PayPal Payments Pro" with slightly different fees/features.  Old users are grandfathered in with the original fees/features, but new users can only get this with the current fees/features.  However, in terms of website integration, I believe the old "PayPal PayFlow Link" API still works with the new "PayPal Payments Pro" product.  (I don't use this myself so I don't know for sure, but as far as I can tell from the documentation it should still work.)
The Tendenci instructions say that "Merchant Account" should be set to "paypal" to use this integration, but that is incorrect; "Merchant Account" should be set to "paypalpayflowlink" to use this integration.

I have also looked into integrating PayPal Express Checkout into Tendenci, as it appears like it would provide a better user experience than the current PayPal Payments Standard integration.  (eg Some of our users have forgotten that they have a PayPal account and are then confused when they are taken to the PayPal login page instead of the credit card form - Express Checkout allows you to override the standard behavior and send users directly to the credit card form even if they have a PayPal account.)  However, I haven't actually implemented that either.

**Comment by goetzk** [comment]
Great information, thanks Paul!

**Comment by eschipul** [comment]
I'll let Jenny chime in on this one but at a high level my thoughts are:

1a) We'd love to have a pull request to the docs for those one-offs and translation @PaulSD . I do realize you are busy. Maybe we can just link to this issue from the readthedocs? Perhaps not a standard thing to do, but it would direct people to the solution in the interim.

My thoughts:

1) I love Paypal for their international and global focus. I do not love paypal's lack of foresight and standardization on an API taxonomy that will hand changes to the API (functions accept args and kwargs for a reason, and I see no reason for an encrypted POST API call to be any different.

2) Our team simply can't support the constant changes to the API given few people are willing to pay their fees. Again, Paypal fees are much higher than Stripe for a comparable product.

3) I'm always wary of vendor lockin, including with Stripe. That is why recurring revenue should be handled by Tendenci itself, tokenized of course, but not using the (recent) recurring billing options within Stipe itself. Stripe just raised our fees which I'm not pleased with. Chargify went down this path, added a bunch of stuff our clients didn't want or need, and then tripled their fees. Extracting clients from Chargify to Stipe was difficult and I haven't forgotten the painful expense and wasted time caused by Chargify not giving us an option to continue to use their baseline product. (Tip of the hat to Heroku for teaching me the danger of "walled gardens" and their lock-in expenses! Uuuugh.)

Further PayPal has a much higher "abandon rate" even if the user pays because of the incessant cross-selling promoting their credit cards. I've kind of thrown up my hands and am mostly leaving it up to the community, or paypal itself, to write the integrations and make the pull requests.

From experience I've had clients say phrases like "this is really important to the BOD and they just can't move forward without it". When a reply of "OK, we understand. The estimate is $5k or 2.5k (or even only $500)." Then it becomes "oh, it's not that important."

I do like PayPal despite their fees. I do NOT like their cross selling causing higher abandon payment rates and making NPOs/NGOs waste time with bank rec. And their team could do a better job with consistency with something as simple as XML or JSON payloads to avoid the need for modifications. Better yet, Paypal could write and support their integration with Tendenci and submit a pull request. The project is getting quite large and the respect and help would be mutually beneficial.

Ed

**Comment by goetzk** [comment]
@eschipul would you be willing to accept a replacement for the tendenci.com doco I linked at the start? (https://www.tendenci.com/help-files/setting-up-online-payment-processor-and-merchant-provider-on-a-tendenci-site/).
I'm happy to essentially copy+paste it in to readthedocs followed by an update which includes @PaulSD 's fixes (and an updated header section and blah blah). You'd then need to redirect the existing page to readthedocs or accept a mostly-duplicate.

**Comment by jennyq** [comment]
@goetzk, thank you! I'd say go for it. Thanks @PaulSD for the updated instructions!

**Comment by PaulSD** [comment]
Yeah, if we can move that doc to something that has public source code, then either goetzk or I can update it.

My experience with PayPal:
* APIs
  * Their APIs **are** written in a way that allows adding/evolving parameters over time.  However, their APIs **are not** written in a user-experience-agnostic way.  So, for example, switching from a user experience that has the browser navigate from the origin website to PayPal and back requires a very different API than a user experience that has the browser stay on the origin website and open a pop-up or pop-over with the PayPal website in it.  Therefore, PayPal has changed the API several times to change/improve the user experience.  As a developer consuming their APIs, this is definitely annoying.  However, I understand why they did it, and without the benefits of hindsight I'm not sure I could have designed a better API that would have survived the same user experience changes.  To their credit, PayPal does keep the old APIs around for a really long time (as I mentioned above, the current Tendenci integrations still work as-is).  However, to their detriment, after they move on to a new API they seem to abandon the old API and stop adding new features to it (as I mentioned above, there are some new features in the Express Checkout API that would be trivial to implement in the old Payments Standard API too, but they haven't done that).
  * My biggest problem with the old Payments Standard API is that it tends to show the end user an unhelpful generic error message if anything goes wrong.  For example, if Tendenci passes in a state name that PayPal doesn't recognize, and the user pays by credit card without logging into PayPal, and the user doesn't enter a state name on the PayPal credit card form, then the user gets a generic error message that basically just tells them to try again later.  Given technically unsavvy end users whose best description of this error was "I can't renew online because your website always tells me to try again" and who would refuse to answer (or give useless answers to) follow-up questions, it took me a couple days of effort over a couple months of calendar time to figure out what was going on here.  How hard would it have been for PayPal to give a more descriptive error message?!  Or at least have the IPN/callback API send be able to send useful error messages to the website owner so they can do something with that information.  Which reminds me - I have a bunch of changes to the Tendenci PayPal integration code to prevent some of these errors that I need to put into a PR.
* Fees
  * It looks to me like PayPal and Stripe currently have the same fees: https://stripe.com/pricing https://www.paypal.com/en/webapps/mpp/paypal-fees ... Am I missing something?
* Recurring Payments
  * The last time I looked into recurring payments on PayPal (a year or two ago), they had two tiers of services: A standard/limited service, and an "enhanced" service with a monthly fee.  The standard/limited service didn't work for our use case (it gave payees no control over the payments and required having each individual payer change their own settings if anything needed to change on the payee side), and the "enhanced" service was out of our budget.  However, scanning through their website now, it looks like their current "Subscription Payments" service has no extra fees and would probably work for our use case.  I'll have to try it...
* Cross-selling
  * We haven't had any issues with this.  If Tendenci passes an email address associated with a PayPal account, then PayPal does try to coerce the user to log in rather than entering credit card info directly without logging in (which some users find annoying).  If I remember correctly, they might also put a banner or side-bar in one of the pages that advertises PayPal stuff.  However, I haven't heard any complaints about the advertising being intrusive, and I haven't noticed it being intrusive when I've used it myself as an end user.

**Comment by goetzk** [comment]
Thanks everyone for their feedback. I won't be able to submit a PR immediately so I'll close this ticket. Hopefully I remember to notify everyone here when the PR is available in case anyone has further input at that time.
