### ISSUE TITLE
Bug: News app prefixes search title with site Primary Keywords

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#907]
I have no idea who thought this was a good idea:

```
{% firstof trans SITE_GLOBAL_SITEPRIMARYKEYWORDS trans SITE_GLOBAL_SITEDISPLAYNAME %}
```

https://github.com/tendenci/tendenci/blob/e75ed25c7639b74667cfd11ce2e01446de0d4f83/tendenci/themes/t7-base/templates/news/search.html#L24

If you set Primary Keywords for you site in the site settings, they suddenly appear in the heading for the News search. Totally out of place and looking decidedly awkward, not least as these are advertised as metadata on the setting page (stress on the "meta")

Methinks this should just read:

```
{% trans SITE_GLOBAL_SITEDISPLAYNAME   %}
```

**Comment by jennyq** [comment]
I think that is for the SEO purpose. I see your point. Will need @eschipul to weigh in on this.

There is another unrelated issue - The trans tag works only for string literals. The variables are not translatable. So the trans tags should be removed to make it look like:
` {% firstof  SITE_GLOBAL_SITEPRIMARYKEYWORDS  SITE_GLOBAL_SITEDISPLAYNAME %} ` or `{{ SITE_GLOBAL_SITEDISPLAYNAME   }}`.

**Comment by bernd-wechner** [comment]
So we're waiting on @eschipul  ;-). In the mean time work around is, like in the demo, have no  SITE_GLOBAL_SITEPRIMARYKEYWORDS defined. 

I seriously doubt no can imagine, that there was ever any good reason for putting them in the page heading (SEA can work off the meta tags surely) as Global site keywords can be a log comma separated list of keywords I presume (that's what I tried). The very sort of things you want search results to hit on for your site. There's not a snowball's chance in hell I'd want them prefixing the heading on a News search or can imagine who would. So perhaps I am misunderstanding what primary keywords are, and should be ...?

**Comment by eschipul** [comment]
@bernd-wechner @jennyq 

re `{% firstof SITE_GLOBAL_SITEPRIMARYKEYWORDS SITE_GLOBAL_SITEDISPLAYNAME %} or {{ SITE_GLOBAL_SITEDISPLAYNAME }}.`

used on a page like https://demo.tendenci.com/news/

People don't put the word "news about our company" in "news". In fact they rarely even use the words "news" or "press" or "articles" so those modules can and should use the appropriate words for that topic. A great example of this is jobs where the person posting it omits words like "employment" or "job" - hence the system template says things like "Job Description" for the literal.

All of that said, the real Issue is we have two keyword sets built in automatically. And we've either drifted from the intent or they are set incorrectly.

1) SITE_GLOBAL_SITEPRIMARYKEYWORDS - This should be a two word phrase at MOST and is visible on the site in either h1 or h2 tags. 
2) SITE_GLOBAL_SITESECONDARYKEYWORDS - this should be whatever you want, although for good SEO it should match the content of the site as much as possible. Again I recommend limiting this and not getting spammy "foo bar, programming" and stop there. This should NEVER appear in the visible text on a site but rather concatenated at the end of the keywords in meta.

The goal is for a site about "Web Marketing" should have a title, if none other is provided, in the news search like:
"News about Web Marketing" or "Web Marketing News"

I recommend changing your SITE_GLOBAL_SITEPRIMARYKEYWORDS to be more modest and know that they are visible on the page. That is the intent. Some of clients are VERY serious about their SEO and you just can't keep everyone trained. Hence mild automation.

Try searching for "news (your name here)" and see what shows up?

I am open to a more nuanced approach, maybe better explanatory text on the settings page?

**Comment by bernd-wechner** [comment]
Thanks for the clarification. Indeed I think port of call 1 is to make sure the documentation is very clear on what these settings do and are used for. Not least as their naming is very misleading. SITE_GLOBAL_SITEPRIMARYKEYWORDS for example is clearly being used a kind of site name that is used in default labels here and there, and my supposition from its name was simply that it would be a comma separated list of keywords for search engines.

**Comment by jennyq** [comment]
Thanks @eschipul ! The description of the Primary Keywords setting is updated (appended yours) https://github.com/tendenci/tendenci/commit/1a3ef75c818e3d1b583be487a709b6aa569f9e2b

**Comment by eschipul** [comment]
@bernd-wechner I agree that ---> "SITE_GLOBAL_SITEPRIMARYKEYWORDS" is an inconsistent, or at least redundant ("site" twice in addition to "global"?) name. Not sure how it got that way, and I'm not into the blame game so moving forward.

Side note: One of the most ridiculous things I have EVER heard a programmer say to me was 

`We don't need to document the code. Python is easy to read and the commits are the documentation!`

/facepalm/ Needless to say, at 14k+ commits, commits don't really document much except function as a stack trace for errors and mods to find someone to blame, which is mostly a waste of time imho. But I digress.

My point is it was originally just "SITE_PRIMARY_KEYWORDS" to allow for module level over-rides. Then people didn't read the djangoproject docs on template inheritance best practices (block super, etc...) and started putting the site name in primary keywords. Which led to pages with redundant page visible site name and primary keywords. Which then cascaded into removal of site name in many places. It's like playing whack-a-mole. "If you give a mouse a cookie..."

Sorry for the confusion and at least the docs are better thanks to Jenny's update. Closing this one out. #peace
