### ISSUE TITLE
Unrestricted file upload via > admin/case_studies/casestudy/add/

### ISSUE THREAD

**Issue by Simran-cmd** [tendenci/tendenci#920]
_Vulnerability Details_ 

**Name** : Unrestricted file upload/Malicious File Upload 

**Description** : Forced browsing is an attack where the aim is to enumerate and access/download resources that are not referenced by the application, but are still accessible. Here we can able to download the private files without any authentication.
 
**Impact** : The vulnerability allows an attacker to inject malicious files which could result in defacement, user redirection to a malicious webpage/website etc. Attacker may deface the site by overwriting existing files, or even execute arbitrary code by uploading script files or binaries and tricking the server into executing them.

**Use Case Scenario** :  If anyone has bad intentions, they can upload a php or exe with a trojan and storing it on your website. They can then send the link of the file to any tendenci user saying that it's a new special update and since the file is on www.tendenci,com  the file is trustworthy.

**Vulnerable URL** : https://demo.tendenci.com/admin/case_studies/casestudy/add/

**Vulnerable Parameters** : Image

**Steps to Reproduce** :
1.Login to the demo application, go to 'case_studies' module and select add case study option.
2.Scroll down to image section , and browse any image( in my case, I have uploaded a malicious test zip file in the image upload section)
3.Fill the other details, and save the details.
4.Go to the list again, and we can see that our file is loaded as a image upon clicking it, the user can view the file, and while editing, we can copy the location of the uploaded image/file and paste it in a private browser where the user is not logged in.
5. We are able to download the file without any authentication required/ no login.

**Reference** : https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload
P.S. I have been trying to test this site since the morning, but I feel the demo site logs have been continuously on watch(which is a good thing in this case). Earlier I was able to upload a backoor.php file as well , not it is fixed partially.

**POC** :
![M1](https://user-images.githubusercontent.com/63577507/97553500-83950800-19fb-11eb-838d-61daabb4b3a4.png)
![M2](https://user-images.githubusercontent.com/63577507/97553507-84c63500-19fb-11eb-9c25-75bc8fc07d2e.png)
![M3](https://user-images.githubusercontent.com/63577507/97553510-855ecb80-19fb-11eb-8e09-2897cf2ed29f.png)
![M4](https://user-images.githubusercontent.com/63577507/97553511-855ecb80-19fb-11eb-8aca-e70e67b07a9d.png)
![M5](https://user-images.githubusercontent.com/63577507/97553514-85f76200-19fb-11eb-8fcb-f54e76f97ab4.png)

**Comment by jennyq** [comment]
Resolved. @Simran-cmd, thank you for reporting the issue!

**Comment by eschipul** [comment]
@Simran-cmd Thank you for reporting the security issue. It is only with contributions from the open source community that we can all be sure of the security of open source software. One of the very reasons we are open source!

**PHP files - are blocked**
We do have extensive logging on our network and all php extensions ARE blocked. For example https://demo.tendenci.com/test.php - returns a 444 error.
https://demo.tendenci.com/index.php - to handle converted wordpress sites redirects to "/"
https://demo.tendenci.com/blah/blah/index.php - returns a 404 error

**ZIP files - a super_user can upload a zip file**. 
This is by design. In this case you were logged in to the demo site as an ADMIN, which does have permissions and there are valid business cases for people to download zip files. If a super_user account password is compromised on a "real" site that is a human problem of a compromised password or misconfigured reverse proxy.

YOU DO MAKE A VERY VALID POINT that because that zip file is on demo . tendenci . com and could potentially be available for up to two hours (the container resets every two hours), I can see that there is a window of opportunity for a phishing scammer to use that to try to trick someone based on our site's domain authority. 

In the case of the **demo** site I see no reason to allow zip file uploads or downloads. Therefore I will take your advice and block them. This is the same reason the demo site doesn't send emails - bad actors would try to use it as an email relay.

A HUGE THANK YOU! - Ed

If possible, please adhere to Django's "responsible reporting" methodology as we do: [https://docs.djangoproject.com/en/dev/internals/security/#reporting-security-issues](https://docs.djangoproject.com/en/dev/internals/security/#reporting-security-issues
)
If we had ignored it (we didn't), I can see elevating it in priority and posting it publicly for the sake of the community. 
[https://en.wikipedia.org/wiki/Responsible_disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure)
Our security practices are listed publicly here, in general terms obviously to prevent over-disclosure of our cloud config.
[https://www.tendenci.com/security/](https://www.tendenci.com/security/)

Thank you again!

**Comment by Simran-cmd** [comment]
Hi Team, 
Hope you're doing well!
Considering the above issue, I have reported a security vulnerability in your open Source project.
I have a small request if you could please create a security advisory in your project for the same. This would help me in getting a CVE ID for the reported vulnerability. Getting a CVE ID for a security researcher is nothing but just a small appreciation and also adds a lot of value for the contribution one does to the development community.

Below are some links which might be helpful:
https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/about-github-security-advisories
https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory

Please let me know if you need any help in this case.

Thanks & Regards,
Simran

**Comment by Simran-cmd** [comment]
@jennyq Thankyou for the quick response and such immediate action , I will once again try to cross check and update you if possible and @eschipul I really appreciate the time you have taken out to respond, means a lottt :D 
@lashirley21 Thankyou.

**Comment by Simran-cmd** [comment]
@eschipul Sorry if this public issue reporting caused you any trouble. This wasn't the intention. I tried to check for the responsible email / platform to submit the issue but didn't find one. Hence followed the given link instructions : https://github.com/tendenci/tendenci/security/policy
Feel free to provide me any assistance required in order to remove the issue from the public platform.

**Comment by eschipul** [comment]
@Simran-cmd Thank you again and that is an excellent suggestion that we somehow missed! If you want to do a pull request so that it can be properly attributed to do on your github reputation we'd love to merge. 

I can certainly add it as well, and with credit and thanks to you for the suggestion and referencing this issue. I'm not kidding when I say I truly appreciate it. Tendenci is a tiny company behind a large community dominated by giant companies that don't always have non-profit's best interests at heart.

No matter what, I do feel giving you credit for the catch and the omission. A lot of people watch our project pretty closely but I'd much rather deal with a concerned email than miss a security issue!

**Comment by Simran-cmd** [comment]
@eschipul Thankyou! 
From my understanding about the pull request, I have forked the repository , Can you please explain what needs to be done next in order to merge into the pull request?

**Comment by Simran-cmd** [comment]
Hi @jennyq , Can you please update regarding the CVE Id?
